EDLUTKernel: src/EDLUTKernel.cpp File Reference
src/EDLUTKernel.cpp File Reference
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <time.h>
#include <math.h>
#include <iostream>
#include "./simulation/include/ParamReader.h"
#include "./simulation/include/Simulation.h"
#include "./simulation/include/ParameterException.h"
#include "./communication/include/ConnectionException.h"
#include "./spike/include/EDLUTFileException.h"
#include "./spike/include/EDLUTException.h"
#include "./spike/include/Network.h"
Functions
int main (int ac, char *av[])
Function Documentation
int main (int ac, char * av[])
Note:
Obligatory parameters: -time Simulation_Time(in_seconds) It sets the total simulation time. -nf Network_File It sets the network description file. -wf Weights_File It sets the weights file.
parameters: -info It shows the network information. -sf File_Name It saves the final weights in file File_Name. -wt Save_Weight_Step It sets the step time between weights saving. -st Step_Time(in_seconds) It sets the step time in simulation. -log File_Name It saves the activity register in file File_Name. -if Input_File It adds the Input_File file in the input sources of the simulation. -of Output_File It adds the Output_File file in the output targets of the simulation. -ic IPDirection:Port Server|Client It adds the connection as a server or a client in the specified address in the input sources of the simulation. -oc IPDirection:Port Server|Client It adds the connection as a server or a client in the specified address in the output targets of the simulation. -ioc IPDirection:Port Server|Client It adds the connection as a server or a client in the specified address in the input sources and in the output targets of the simulation.
Definition at line 44 of file EDLUTKernel.cpp.
References ParamReader::CheckInfo(), EDLUTException::GetErrorNum(), ParamReader::GetInputSpikeDrivers(), ParamReader::GetMonitorDrivers(), ParamReader::GetNetworkFile(), ParamReader::GetOutputSpikeDrivers(), ParamReader::GetOutputWeightDrivers(), ParamReader::GetSaveWeightStepTime(), ParamReader::GetSimulationStepTime(), ParamReader::GetSimulationTime(), and ParamReader::GetWeightsFile().