EDLUTKernel: MultiplicativeWeightChange Class Reference
MultiplicativeWeightChange Class Reference
Multiplicative learning rule.
#include <MultiplicativeWeightChange.h>
Public Member Functions
virtual void ApplyWeightChange (Interconnection *Connection, double SpikeTime)
It applys the weight change function.
Detailed Description
Multiplicative learning rule.
This class abstract the behaviour of a multiplicative learning rule.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 27 of file MultiplicativeWeightChange.h.
Member Function Documentation
void MultiplicativeWeightChange::ApplyWeightChange (Interconnection * Connection, double SpikeTime) [virtual]
It applys the weight change function.
It applys the weight change function.
Parameters:
Connection The connection where the spike happened.
SpikeTime The spike time.
Implements WeightChange.
Definition at line 8 of file MultiplicativeWeightChange.cpp.
References WeightChange::GetA1Pre(), WeightChange::GetA2PrePre(), Interconnection::GetActivityAt(), WeightChange::GetCparAt(), Neuron::GetInputConnectionAt(), Neuron::GetInputNumber(), Interconnection::GetLastSpikeTime(), WeightChange::GetLparAt(), Interconnection::GetMaxWeight(), WeightChange::GetNumExps(), Interconnection::GetTarget(), Interconnection::GetWeight(), Interconnection::GetWeightChange(), Interconnection::SetActivityAt(), Interconnection::SetLastSpikeTime(), and Interconnection::SetWeight().
The documentation for this class was generated from the following files:
src/spike/include/MultiplicativeWeightChange.h
src/spike/MultiplicativeWeightChange.cpp