EDLUTKernel: Simulation Class Reference
Simulation Class Reference
Spiking neural network simulation.
#include <Simulation.h>
Public Member Functions
Simulation (const char *NetworkFile, const char *WeightsFile, double SimulationTime, double NewSimulationStep=0.00) throw (EDLUTException)
Class constructor with parameters.
Simulation (const Simulation &ant)
Copy constructor of the class.
~Simulation ()
Object destructor.
void SetSaveStep (float NewSaveStep)
It sets the saving weights step time.
double GetSaveStep ()
It gets the saving weights step time.
void SetSimulationStep (double NewSimulationStep)
It sets the simulation step time.
double GetSimulationStep ()
It gets the simulation step time.
void EndSimulation ()
It ends the simulation before the next event.
void AddInputSpikeDriver (InputSpikeDriver *NewInput)
It adds a new input driver to the input driver list.
void RemoveInputSpikeDriver (InputSpikeDriver *NewInput)
It removes an input driver of the input driver list.
void AddOutputSpikeDriver (OutputSpikeDriver *NewOutput)
It adds a new output driver to the output driver list.
void RemoveOutputSpikeDriver (OutputSpikeDriver *NewOutput)
It removes an output driver of the output driver list.
void AddMonitorActivityDriver (OutputSpikeDriver *NewMonitor)
It adds a new output driver to the monitor activity list.
void RemoveMonitorActivityDriver (OutputSpikeDriver *NewMonitor)
It removes an output driver of the output monitor list.
void AddOutputWeightDriver (OutputWeightDriver *NewOutput)
It adds a new output weight driver to the output driver list.
void RemoveOutputWeightDriver (OutputWeightDriver *NewOutput)
It removes an output weight driver of the output driver list.
void RunSimulation () throw (EDLUTException)
It runs the simulation.
void WriteSpike (const Spike *spike)
It writes a spike in the activity log and in the outputs.
void WritePotential (float time, Neuron *neuron, float value)
It writes a neuron potential.
void SaveWeights ()
It saves the current synaptic weights in the output weights driver.
void SendOutput ()
It sends the happened events.
void GetInput ()
It gets the input activity.
Network * GetNetwork () const
It gets the simulated network.
EventQueue * GetQueue () const
It gets the event queue.
double GetTotalSimulationTime () const
It gets the stablished simulation time.
long long GetSimulationUpdates () const
It gets the number of simulation updates realized.
long long GetHeapAcumSize () const
It gets the sumatory of event queue sizes.
Protected Member Functions
void RunSimulationStep () throw (EDLUTException)
It realizes the main process of simulation.
Private Attributes
Network * Net
EventQueue * Queue
list
< InputSpikeDriver * > InputSpike
list
< OutputSpikeDriver * > OutputSpike
list
< OutputWeightDriver * > OutputWeight
list
< OutputSpikeDriver * > MonitorSpike
double Totsimtime
double SimulationStep
double SaveWeightStep
double CurrentSimulationTime
bool EndOfSimulation
long long Updates
long long Heapoc
Detailed Description
Spiking neural network simulation.
This class abstract the behaviour of a spiking neural network simulation. It loads the network, gets the input spikes and finally produces the output spikes. Moreover, this class generates some simulation statistics.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 40 of file Simulation.h.
Constructor & Destructor Documentation
Simulation::Simulation (const char * NetworkFile, const char * WeightsFile, double SimulationTime, double NewSimulationStep = 0.00) throw (EDLUTException)
Class constructor with parameters.
It creates a new object an initilizes its elements.
Parameters:
NetworkFile Network description file name. The network will be loaded from this file.
WeightsFile Weights description file name. The network synaptic weights will be loaded from this file.
SimulationTime Simulation total time.
NewSimulationStep Simulation step time.
throw EDLUTException If something wrong happens.
Definition at line 16 of file Simulation.cpp.
Simulation::Simulation (const Simulation & ant)
Copy constructor of the class.
It creates a new object copied of the parameter.
Parameters:
ant Current simulation object (copy source).
Definition at line 21 of file Simulation.cpp.
Simulation::~Simulation ()
Object destructor.
It destroys an object of Simulation class.
Definition at line 24 of file Simulation.cpp.
Member Function Documentation
void Simulation::RunSimulationStep () throw (EDLUTException) [protected]
It realizes the main process of simulation.
It propagates the spikes after the input is loaded. This propagation ends when the simulation time is higher than the total simulation time or when no more activity is produced.
Precondition:
The activity has been previously loaded.
Exceptions:
EDLUTException If something wrong happends in the spike propagation process.
void Simulation::SetSaveStep (float NewSaveStep)
It sets the saving weights step time.
It sets the saving weights step time.
Parameters:
NewSaveStep The saving step time (in seconds). 0 values don't save the weights.
Definition at line 31 of file Simulation.cpp.
References SaveWeightStep.
double Simulation::GetSaveStep ()
It gets the saving weights step time.
It gets the saving weights step time.
Returns:
The saving step time (in seconds). 0 values don't save the weights.
Definition at line 35 of file Simulation.cpp.
References SaveWeightStep.
Referenced by SaveWeightsEvent::ProcessEvent().
void Simulation::SetSimulationStep (double NewSimulationStep)
It sets the simulation step time.
It sets the saving step time.
Parameters:
NewSimulationStep The simulation step time (in seconds). 0 values don't simulate by steps.
Definition at line 39 of file Simulation.cpp.
References SimulationStep.
double Simulation::GetSimulationStep ()
It gets the simulation step time.
It gets the simulation step time.
Returns:
The simulation step time (in seconds). 0 values don't simulate by step.
Definition at line 43 of file Simulation.cpp.
References SimulationStep.
Referenced by CommunicationEvent::ProcessEvent().
void Simulation::EndSimulation ()
It ends the simulation before the next event.
It ends the simulation before the next event.
Definition at line 27 of file Simulation.cpp.
References EndOfSimulation.
Referenced by EndSimulationEvent::ProcessEvent().
void Simulation::AddInputSpikeDriver (InputSpikeDriver * NewInput)
It adds a new input driver to the input driver list.
It adds a new input driver to the input driver list.
Parameters:
NewInput The input driver to add.
Definition at line 170 of file Simulation.cpp.
void Simulation::RemoveInputSpikeDriver (InputSpikeDriver * NewInput)
It removes an input driver of the input driver list.
It removes an input driver of the input driver list.
Parameters:
NewInput The input driver to remove.
Definition at line 174 of file Simulation.cpp.
void Simulation::AddOutputSpikeDriver (OutputSpikeDriver * NewOutput)
It adds a new output driver to the output driver list.
It adds a new output driver to the output driver list.
Parameters:
NewOutput The Output driver to add.
Definition at line 178 of file Simulation.cpp.
References OutputSpike.
void Simulation::RemoveOutputSpikeDriver (OutputSpikeDriver * NewOutput)
It removes an output driver of the output driver list.
It removes an output driver of the output driver list.
Parameters:
NewOutput The output driver to remove.
Definition at line 182 of file Simulation.cpp.
References OutputSpike.
void Simulation::AddMonitorActivityDriver (OutputSpikeDriver * NewMonitor)
It adds a new output driver to the monitor activity list.
It adds a new output driver to the monitor activity list.
Parameters:
NewMonitor The Output driver to add.
Definition at line 186 of file Simulation.cpp.
References MonitorSpike.
void Simulation::RemoveMonitorActivityDriver (OutputSpikeDriver * NewMonitor)
It removes an output driver of the output monitor list.
It removes an output driver of the output monitor list.
Parameters:
NewMonitor The output driver to remove.
Definition at line 190 of file Simulation.cpp.
References MonitorSpike.
void Simulation::AddOutputWeightDriver (OutputWeightDriver * NewOutput)
It adds a new output weight driver to the output driver list.
It adds a new output driver to the output driver list.
Parameters:
NewOutput The Output driver to add.
Definition at line 194 of file Simulation.cpp.
References OutputWeight.
void Simulation::RemoveOutputWeightDriver (OutputWeightDriver * NewOutput)
It removes an output weight driver of the output driver list.
It removes an output driver of the output driver list.
Parameters:
NewOutput The output driver to remove.
Definition at line 198 of file Simulation.cpp.
References OutputWeight.
void Simulation::RunSimulation () throw (EDLUTException)
It runs the simulation.
It runs the simulation.
Exceptions:
EDLUTException If something wrong happens.
Definition at line 47 of file Simulation.cpp.
References CurrentSimulationTime, GetInput(), Event::GetTime(), Heapoc, EventQueue::InsertEvent(), Event::ProcessEvent(), Queue, EventQueue::RemoveEvent(), EventQueue::Size(), and Updates.
void Simulation::WriteSpike (const Spike * spike)
It writes a spike in the activity log and in the outputs.
It writes a spike in the activity log and in the outputs.
Parameters:
spike The spike to be wrotten.
Definition at line 90 of file Simulation.cpp.
References Spike::GetSource(), Neuron::IsMonitored(), Neuron::IsOutput(), MonitorSpike, and OutputSpike.
Referenced by InternalSpike::ProcessEvent(), and InputSpike::ProcessEvent().
void Simulation::WritePotential (float time, Neuron * neuron, float value)
It writes a neuron potential.
It writes a neuron potential.
Parameters:
time The event time.
neuron The neuron of the event.
value The value of the potential.
Definition at line 106 of file Simulation.cpp.
References Neuron::IsMonitored(), Neuron::IsOutput(), MonitorSpike, and OutputSpike.
Referenced by PropagatedSpike::ProcessEvent(), InternalSpike::ProcessEvent(), and InputSpike::ProcessEvent().
void Simulation::SaveWeights ()
It saves the current synaptic weights in the output weights driver.
It saves the current synaptic weights in the output weights driver.
Definition at line 124 of file Simulation.cpp.
References CurrentSimulationTime, and OutputWeight.
Referenced by SaveWeightsEvent::ProcessEvent().
void Simulation::SendOutput ()
It sends the happened events.
It sends the happened events.
Definition at line 132 of file Simulation.cpp.
References CurrentSimulationTime, and OutputSpike.
Referenced by CommunicationEvent::ProcessEvent().
void Simulation::GetInput ()
It gets the input activity.
It gets the input activity.
Definition at line 141 of file Simulation.cpp.
References CurrentSimulationTime.
Referenced by CommunicationEvent::ProcessEvent(), and RunSimulation().
Network * Simulation::GetNetwork () const
It gets the simulated network.
It gets the simulated network.
Returns:
The simulated network.
Definition at line 150 of file Simulation.cpp.
References Net.
EventQueue * Simulation::GetQueue () const
It gets the event queue.
It gets the event queue.
Returns:
The simulated network.
Definition at line 154 of file Simulation.cpp.
References Queue.
Referenced by PropagatedSpike::ProcessEvent(), InternalSpike::ProcessEvent(), InputSpike::ProcessEvent(), SaveWeightsEvent::ProcessEvent(), and CommunicationEvent::ProcessEvent().
double Simulation::GetTotalSimulationTime () const
It gets the stablished simulation time.
It gets the total simulation time.
Returns:
The total simulation time.
Definition at line 158 of file Simulation.cpp.
References Totsimtime.
long long Simulation::GetSimulationUpdates () const
It gets the number of simulation updates realized.
It gets the number of simulation updates realized.
Returns:
The number of simulation updates.
Definition at line 162 of file Simulation.cpp.
References Updates.
long long Simulation::GetHeapAcumSize () const
It gets the sumatory of event queue sizes.
It gets the sumatory of event queue sizes.
Returns:
The number of acumulated event queue sizes.
Definition at line 166 of file Simulation.cpp.
References Heapoc.
Member Data Documentation
Network* Simulation::Net [private]
Neural network to simulate.
Definition at line 46 of file Simulation.h.
Referenced by GetNetwork().
EventQueue* Simulation::Queue [private]
Event queue used in the events.
Definition at line 51 of file Simulation.h.
Referenced by GetQueue(), and RunSimulation().
list<InputSpikeDriver *> Simulation::InputSpike [private]
Input of activity.
Definition at line 56 of file Simulation.h.
list<OutputSpikeDriver *> Simulation::OutputSpike [private]
Output of activity.
Definition at line 61 of file Simulation.h.
Referenced by AddOutputSpikeDriver(), RemoveOutputSpikeDriver(), SendOutput(), WritePotential(), and WriteSpike().
list<OutputWeightDriver *> Simulation::OutputWeight [private]
Output of activity.
Definition at line 66 of file Simulation.h.
Referenced by AddOutputWeightDriver(), RemoveOutputWeightDriver(), and SaveWeights().
list<OutputSpikeDriver *> Simulation::MonitorSpike [private]
Monitor of activity.
Definition at line 71 of file Simulation.h.
Referenced by AddMonitorActivityDriver(), RemoveMonitorActivityDriver(), WritePotential(), and WriteSpike().
double Simulation::Totsimtime [private]
Total time of simulation.
Definition at line 76 of file Simulation.h.
Referenced by GetTotalSimulationTime().
double Simulation::SimulationStep [private]
Simulation step
Definition at line 81 of file Simulation.h.
Referenced by GetSimulationStep(), and SetSimulationStep().
double Simulation::SaveWeightStep [private]
Save weight step
Definition at line 86 of file Simulation.h.
Referenced by GetSaveStep(), and SetSaveStep().
double Simulation::CurrentSimulationTime [private]
Current simulation Time
Definition at line 91 of file Simulation.h.
Referenced by GetInput(), RunSimulation(), SaveWeights(), and SendOutput().
bool Simulation::EndOfSimulation [private]
End of simulation
Definition at line 96 of file Simulation.h.
Referenced by EndSimulation().
long long Simulation::Updates [private]
Number of realized updates.
Definition at line 101 of file Simulation.h.
Referenced by GetSimulationUpdates(), and RunSimulation().
long long Simulation::Heapoc [private]
Sumatory of heap size.
Definition at line 106 of file Simulation.h.
Referenced by GetHeapAcumSize(), and RunSimulation().
The documentation for this class was generated from the following files:
src/simulation/include/Simulation.h
src/simulation/Simulation.cpp