EDLUTKernel: Interconnection Class Reference
Interconnection Class Reference
Spiking neural network connection.
#include <Interconnection.h>
Public Member Functions
Interconnection ()
Default constructor.
Interconnection (int NewIndex, Neuron *NewSource, Neuron *NewTarget, float NewDelay, int NewType, float NewWeight, float NewMaxWeight, WeightChange *NewWeightChange, float NewActivity[3], float NewLastSpikeTime)
Constructor with parameters.
long int GetIndex () const
It gets the connection index.
void SetIndex (long int NewIndex)
It sets the connection index.
Neuron * GetSource () const
It gets the source neuron.
void SetSource (Neuron *NewSource)
It sets the source neuron.
Neuron * GetTarget () const
It gets the target neuron.
void SetTarget (Neuron *NewTarget)
It sets the target neuron.
double GetDelay () const
It gets the connection delay.
void SetDelay (float NewDelay)
It sets the connection delay.
int GetType () const
It gets the connection type.
void SetType (int NewType)
It sets the connection type.
float GetWeight () const
It gets the synaptic weight.
void SetWeight (float NewWeight)
It sets the synaptic weight.
float GetMaxWeight () const
It gets the maximum synaptic weight.
void SetMaxWeight (float NewMaxWeight)
It sets the maximum synaptic weight.
WeightChange * GetWeightChange () const
It gets the learning rule of this connection.
void SetWeightChange (WeightChange *NewWeightChange)
It sets the learning rule of this connection.
void ClearActivity ()
It clears the activity register of this connection.
float GetActivityAt (int index) const
It gets the activity in an specified index.
void SetActivityAt (int index, float NewActivity)
It sets the activity in an specified index.
double GetLastSpikeTime () const
It gets the time of the last propagated spike.
void SetLastSpikeTime (double NewTime)
It sets the time of the last propagated spike.
void ChangeWeights (double stime)
It modifies the synaptic weight of this connection.
Private Attributes
Neuron * source
The source neuron of the connection.
Neuron * target
The target neuron of the connection.
long int index
The index of the connection in the network connections.
double delay
The delay of the spike propagation.
int type
The connection type (excitatory, inhibitory, electrical coupling...).
float weight
The synaptic weight of the connection.
float maxweight
The maximum weight of the connection.
WeightChange * wchange
The learning (or weight change) rule of the connection.
float activity [3]
The activity register of the connection. The last three activities.
double lastspiketime
The time of the last fired spike.
Detailed Description
Spiking neural network connection.
This class abstract the behaviour of a spiking neural network connection. It is composed by source and target neuron, an index, a connection delay...
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 30 of file Interconnection.h.
Constructor & Destructor Documentation
Interconnection::Interconnection ()
Default constructor.
It creates a new interconnection object without source or target neuron.
Definition at line 7 of file Interconnection.cpp.
Interconnection::Interconnection (int NewIndex, Neuron * NewSource, Neuron * NewTarget, float NewDelay, int NewType, float NewWeight, float NewMaxWeight, WeightChange * NewWeightChange, float NewActivity[3], float NewLastSpikeTime)
Constructor with parameters.
It creates and initializes a new interconnection object with the parameters.
Parameters:
NewIndex The interconnection index in the network configuration file.
NewSource Source neuron of this connection.
NewTarget Target neuron of this connection.
NewDelay Delay of this connection.
NewType Connection type (excitatory, inhibitory, electrical coupling...) of this connection. The meaning of a value is depend on the neuron model.
NewWeight Synaptic weight of this connection.
NewMaxWeight Maximum synaptic weight of this connection.
NewWeightChange Learning (or weight change) rule associated to this connection.
NewActivity Last activity register of this connection.
NewLastSpikeTime Time of the last propagated spike in this connection.
Definition at line 11 of file Interconnection.cpp.
References activity.
Member Function Documentation
long int Interconnection::GetIndex () const
It gets the connection index.
It gets the connection index in the network connections.
Returns:
The connection index.
Definition at line 18 of file Interconnection.cpp.
References index.
Referenced by Network::SetWeightOrdination().
void Interconnection::SetIndex (long int NewIndex)
It sets the connection index.
It sets the connection index in the network connections.
Parameters:
NewIndex The new index of the connection.
Definition at line 22 of file Interconnection.cpp.
References index.
Referenced by Network::LoadNet().
Neuron * Interconnection::GetSource () const
It gets the source neuron.
It gets the source neuron of the connection.
Returns:
The source neuron of the connection.
Definition at line 26 of file Interconnection.cpp.
References source.
Referenced by Network::FindOutConnections(), and Network::GetNetInfo().
void Interconnection::SetSource (Neuron * NewSource)
It sets the source neuron.
It sets the source neuron of the connection.
Parameters:
NewSource The new source neuron of the connection.
Definition at line 30 of file Interconnection.cpp.
References source.
Referenced by Network::LoadNet().
Neuron * Interconnection::GetTarget () const
It gets the target neuron.
It gets the target neuron of the connection.
Returns:
The target neuron of the connection.
Definition at line 34 of file Interconnection.cpp.
References target.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), Network::FindInConnections(), Network::GetNetInfo(), and PropagatedSpike::ProcessEvent().
void Interconnection::SetTarget (Neuron * NewTarget)
It sets the target neuron.
It sets the target neuron of the connection.
Parameters:
NewTarget The new target neuron of the connection.
Definition at line 38 of file Interconnection.cpp.
References target.
Referenced by Network::LoadNet().
double Interconnection::GetDelay () const
It gets the connection delay.
It gets the delay in the spike propagation through this connection.
Returns:
The connection delay.
Definition at line 42 of file Interconnection.cpp.
References delay.
Referenced by Network::GetNetInfo(), and Neuron::PropagateOutputSpike().
void Interconnection::SetDelay (float NewDelay)
It sets the connection delay.
It sets the delay of the connection.
Parameters:
NewDelay The new connection delay.
Definition at line 46 of file Interconnection.cpp.
References delay.
Referenced by Network::LoadNet().
int Interconnection::GetType () const
It gets the connection type.
It gets the connection type (excitatory, inhibitory, electrical coupling...) of this connection. The meaning of a value is depend on the neuron model.
Returns:
The connection type.
Definition at line 50 of file Interconnection.cpp.
References type.
Referenced by Network::GetNetInfo(), and Neuron::SynapsisEffect().
void Interconnection::SetType (int NewType)
It sets the connection type.
It sets the connection type (excitatory, inhibitory, electrical coupling...) of this connection. The meaning of a value is depend on the neuron model.
Parameters:
NewType The new connection type.
Definition at line 54 of file Interconnection.cpp.
References type.
Referenced by Network::LoadNet().
float Interconnection::GetWeight () const
It gets the synaptic weight.
It gets the synaptic weight of the connection.
Returns:
The synaptic weight.
Definition at line 58 of file Interconnection.cpp.
References weight.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), Network::SaveWeights(), and Neuron::SynapsisEffect().
void Interconnection::SetWeight (float NewWeight)
It sets the synaptic weight.
It sets the synaptic weight of the connection.
Parameters:
NewWeight The new synaptic weight of the connection.
Definition at line 62 of file Interconnection.cpp.
References weight.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), Network::LoadNet(), and Network::LoadWeights().
float Interconnection::GetMaxWeight () const
It gets the maximum synaptic weight.
It gets the maximum synaptic weight of the connection.
Returns:
The maximum synaptic weight.
Definition at line 66 of file Interconnection.cpp.
References maxweight.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), and Network::LoadWeights().
void Interconnection::SetMaxWeight (float NewMaxWeight)
It sets the maximum synaptic weight.
It sets the maximum synaptic weight of the connection.
Parameters:
NewMaxWeight The new maximum synaptic weight of the connection.
Definition at line 70 of file Interconnection.cpp.
References maxweight.
Referenced by Network::LoadNet().
WeightChange * Interconnection::GetWeightChange () const
It gets the learning rule of this connection.
It gets the learning rule of the connection.
Returns:
The learning rule of the connection. 0 if the connection hasn't learning rule.
Definition at line 74 of file Interconnection.cpp.
References wchange.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), and PropagatedSpike::ProcessEvent().
void Interconnection::SetWeightChange (WeightChange * NewWeightChange)
It sets the learning rule of this connection.
It sets the learning rule of the connection.
Parameters:
NewWeightChange The new learning rule of the connection. 0 if the connection hasn't learning rule.
Definition at line 78 of file Interconnection.cpp.
References wchange.
Referenced by Network::LoadNet().
void Interconnection::ClearActivity ()
It clears the activity register of this connection.
It clears the activity register of this connections and sets their values to 0.
Definition at line 82 of file Interconnection.cpp.
References activity.
Referenced by Network::LoadNet().
float Interconnection::GetActivityAt (int index) const
It gets the activity in an specified index.
It gets the activity in an specified index.
Parameters:
index The index of the activity.
Returns:
The activity in that index.
Definition at line 88 of file Interconnection.cpp.
References activity.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), and AdditiveWeightChange::update_activity().
void Interconnection::SetActivityAt (int index, float NewActivity)
It sets the activity in an specified index.
It sets the activity in an specified index.
Parameters:
The index of the activity.
NewActivity The new activity to be changed.
Definition at line 92 of file Interconnection.cpp.
References activity.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), and AdditiveWeightChange::update_activity().
double Interconnection::GetLastSpikeTime () const
It gets the time of the last propagated spike.
It gets the time of the last propagated spike through this connection.
Returns:
The time of the last propagated spike.
Definition at line 96 of file Interconnection.cpp.
References lastspiketime.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), and AdditiveWeightChange::update_activity().
void Interconnection::SetLastSpikeTime (double NewTime)
It sets the time of the last propagated spike.
It sets the time of the last propagated spike through this connection.
Parameters:
NewTime The new time of the last propagated spike.
Definition at line 100 of file Interconnection.cpp.
References lastspiketime.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), and Network::LoadNet().
void Interconnection::ChangeWeights (double stime)
It modifies the synaptic weight of this connection.
It modifies the synaptic weight of this connection according to its learning rule.
Parameters:
stime The current time in the simulation.
Definition at line 104 of file Interconnection.cpp.
References WeightChange::ApplyWeightChange(), and wchange.
Referenced by PropagatedSpike::ProcessEvent().
Member Data Documentation
Neuron* Interconnection::source [private]
The source neuron of the connection.
Definition at line 36 of file Interconnection.h.
Referenced by GetSource(), and SetSource().
Neuron* Interconnection::target [private]
The target neuron of the connection.
Definition at line 41 of file Interconnection.h.
Referenced by GetTarget(), and SetTarget().
long int Interconnection::index [private]
The index of the connection in the network connections.
Definition at line 46 of file Interconnection.h.
Referenced by GetIndex(), and SetIndex().
double Interconnection::delay [private]
The delay of the spike propagation.
Definition at line 51 of file Interconnection.h.
Referenced by GetDelay(), and SetDelay().
int Interconnection::type [private]
The connection type (excitatory, inhibitory, electrical coupling...).
Definition at line 56 of file Interconnection.h.
Referenced by GetType(), and SetType().
float Interconnection::weight [private]
The synaptic weight of the connection.
Definition at line 61 of file Interconnection.h.
Referenced by GetWeight(), and SetWeight().
float Interconnection::maxweight [private]
The maximum weight of the connection.
Definition at line 66 of file Interconnection.h.
Referenced by GetMaxWeight(), and SetMaxWeight().
WeightChange* Interconnection::wchange [private]
The learning (or weight change) rule of the connection.
Definition at line 71 of file Interconnection.h.
Referenced by ChangeWeights(), GetWeightChange(), and SetWeightChange().
float Interconnection::activity[3] [private]
The activity register of the connection. The last three activities.
Definition at line 76 of file Interconnection.h.
Referenced by ClearActivity(), GetActivityAt(), Interconnection(), and SetActivityAt().
double Interconnection::lastspiketime [private]
The time of the last fired spike.
Definition at line 81 of file Interconnection.h.
Referenced by GetLastSpikeTime(), and SetLastSpikeTime().
The documentation for this class was generated from the following files:
src/spike/include/Interconnection.h
src/spike/Interconnection.cpp