EDLUTKernel: PropagatedSpike Class Reference
PropagatedSpike Class Reference
Neural network propagated spike.
#include <PropagatedSpike.h>
Public Member Functions
PropagatedSpike ()
Default constructor.
PropagatedSpike (double NewTime, Neuron *NewSource, int NewTarget)
Constructor with parameters.
~PropagatedSpike ()
Class destructor.
int GetTarget () const
It gets the spike source type.
void SetTarget (int NewTarget)
It sets the spike source type.
virtual void ProcessEvent (Simulation *CurrentSimulation)
It process an event in the simulation.
Protected Attributes
int target
Detailed Description
Neural network propagated spike.
A propagated spike is an event which generates a new spike in the next output connection.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 33 of file PropagatedSpike.h.
Constructor & Destructor Documentation
PropagatedSpike::PropagatedSpike ()
Default constructor.
It creates and initializes a new spike object.
Definition at line 8 of file PropagatedSpike.cpp.
PropagatedSpike::PropagatedSpike (double NewTime, Neuron * NewSource, int NewTarget)
Constructor with parameters.
It creates and initializes a new spike with the parameters.
Parameters:
NewTime Time of the new spike.
NewSource Source neuron of the spike.
NewTarget >0->Interneurons spike.
Definition at line 11 of file PropagatedSpike.cpp.
PropagatedSpike::~PropagatedSpike ()
Class destructor.
It destroies an object of this class.
Definition at line 14 of file PropagatedSpike.cpp.
Member Function Documentation
int PropagatedSpike::GetTarget () const
It gets the spike source type.
It gets the spike source type.
Returns:
The spike source type: -1->Input spike, -2->Internal spike and >0->Interneurons spike.
Definition at line 17 of file PropagatedSpike.cpp.
References target.
Referenced by Neuron::ProcessInputSynapticActivity(), and Neuron::PropagateOutputSpike().
void PropagatedSpike::SetTarget (int NewTarget)
It sets the spike source type.
It sets the spike source type.
Parameters:
NewTarget The new spike source type: -1->Input spike, -2->Internal spike and >0->Interneurons spike.
Definition at line 21 of file PropagatedSpike.cpp.
References target.
void PropagatedSpike::ProcessEvent (Simulation * CurrentSimulation) [virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implements Spike.
Definition at line 25 of file PropagatedSpike.cpp.
References Interconnection::ChangeWeights(), Neuron::GenerateInputActivity(), Neuron::GetOutputConnectionAt(), Simulation::GetQueue(), Neuron::GetStateVarAt(), Interconnection::GetTarget(), Interconnection::GetWeightChange(), Neuron::ProcessInputSynapticActivity(), Neuron::PropagateOutputSpike(), Spike::source, and Simulation::WritePotential().
Member Data Documentation
int PropagatedSpike::target [protected]
>0: Interneurons spike.
Definition at line 39 of file PropagatedSpike.h.
Referenced by GetTarget(), and SetTarget().
The documentation for this class was generated from the following files:
src/spike/include/PropagatedSpike.h
src/spike/PropagatedSpike.cpp