EDLUTKernel: EDLUTException Class Reference
EDLUTException Class Reference
Exception in the simulation process.
#include <EDLUTException.h>
Public Member Functions
EDLUTException (int a, int b, int c, int d)
Class constructor.
long GetErrorNum () const
It gets the error number.
const char * GetTaskMsg () const
It gets the task message.
const char * GetErrorMsg () const
It gets the error message.
const char * GetRepairMsg () const
It gets the repair message.
void display_error () const
It prints in the standard error the error message of this exception.
Private Member Functions
long GetErrorValue (int a, int b, int c, int d)
It gets an only long number from four integer values.
Private Attributes
int ErrorNum
Static Private Attributes
static const char * Taskmsgs []
static const char * Errormsgs []
static const char * Repairmsgs []
Detailed Description
Exception in the simulation process.
This class abstract the behaviour of an exception in the EDLUT simulation process. This exception could happen by different reasons (not found files, bad input spikes, not enough memory...). When an exception is thrown, the simulation is stopped without results.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 33 of file EDLUTException.h.
Constructor & Destructor Documentation
EDLUTException::EDLUTException (int a, int b, int c, int d)
Class constructor.
Class constructor with parameters.
Parameters:
a The most significant integer. Task number.
b The second most significant integer. Error number.
c The third most significant integer. Repair number.
d The less significant integer.
Definition at line 105 of file EDLUTException.cpp.
References ErrorNum, and GetErrorValue().
Member Function Documentation
long EDLUTException::GetErrorValue (int a, int b, int c, int d) [private]
It gets an only long number from four integer values.
It gets an only long number from four integer values.
Parameters:
a The most significant integer. Task number.
b The second most significant integer. Error number.
c The third most significant integer. Repair number.
d The less significant integer.
Returns:
The error value from the four integer values.
Definition at line 101 of file EDLUTException.cpp.
Referenced by EDLUTException().
long EDLUTException::GetErrorNum () const
It gets the error number.
It gets the error number.
Returns:
The error number.
Definition at line 109 of file EDLUTException.cpp.
References ErrorNum.
Referenced by main(), and operator<<().
const char * EDLUTException::GetTaskMsg () const
It gets the task message.
It gets the task that threw the error.
Returns:
The task message.
Definition at line 113 of file EDLUTException.cpp.
References ErrorNum, and Taskmsgs.
Referenced by operator<<().
const char * EDLUTException::GetErrorMsg () const
It gets the error message.
It gets the error message.
Returns:
The error message.
Definition at line 117 of file EDLUTException.cpp.
References Errormsgs, and ErrorNum.
Referenced by EDLUTFileException::display_error(), and operator<<().
const char * EDLUTException::GetRepairMsg () const
It gets the repair message.
It gets the repair message.
Returns:
The repair message.
Definition at line 121 of file EDLUTException.cpp.
References ErrorNum, and Repairmsgs.
Referenced by operator<<().
void EDLUTException::display_error () const
It prints in the standard error the error message of this exception.
It prints in the standard error the error message of this exception.
Reimplemented in EDLUTFileException.
Definition at line 125 of file EDLUTException.cpp.
Member Data Documentation
int EDLUTException::ErrorNum [private]
Number of error.
Definition at line 39 of file EDLUTException.h.
Referenced by EDLUTException(), GetErrorMsg(), GetErrorNum(), GetRepairMsg(), and GetTaskMsg().
const char * EDLUTException::Taskmsgs [static, private]
Initial value:
{
        "",
        "Inserting a spike into the heap",
        "Initializing the output",
        "Putting a spike out",
        "Loading the net configuration file",
        "Initializing the spikes heap",
        "Loading the input spikes from file",
        "Scaling neuron tables",
        "Generating the spike prediction time table",
        "Loading neuron table",
        "Loading neuron tables",
        "Loading weights from file",
        "Saving weights to file",
        "Loading the neuron type configuration"
}
Task messages.
Definition at line 58 of file EDLUTException.h.
Referenced by GetTaskMsg().
const char * EDLUTException::Errormsgs [static, private]
Error messages.
Definition at line 63 of file EDLUTException.h.
Referenced by GetErrorMsg().
const char * EDLUTException::Repairmsgs [static, private]
Repair messages.
Definition at line 68 of file EDLUTException.h.
Referenced by GetRepairMsg().
The documentation for this class was generated from the following files:
src/spike/include/EDLUTException.h
src/spike/EDLUTException.cpp