EDLUTKernel: Neuron Class Reference
Neuron Class Reference
Spiking neuron.
#include <Neuron.h>
Public Member Functions
Neuron ()
Default constructor without parameters.
Neuron (int NewIndex, NeuronType *Type, bool Monitored, bool IsOutput)
Neuron constructor with parameters.
void InitNeuron (int NewIndex, NeuronType *Type, bool Monitored, bool IsOutput)
It initializes the neuron values.
void InitNeuronPrediction (EventQueue *eventQueue)
It generates the initial neuron activity.
void GenerateAutoActivity (EventQueue *eventQueue)
It generates the next spike in the neuron without input activity.
void ProcessInputActivity (InternalSpike *InputSpike)
It updates the neural state after an input spike.
void ProcessInputSynapticActivity (PropagatedSpike *InputSpike)
It updates the neural state after a synaptic input spike (target neuron).
void GenerateOutputActivity (Spike *InputSpike, EventQueue *eventQueue)
It generates the first output spike.
void PropagateOutputSpike (PropagatedSpike *LastSpike, EventQueue *eventQueue)
It propagates an output spike.
void GenerateInputActivity (EventQueue *eventQueue)
It checks if a new spike will be fired.
long int GetIndex () const
It gets the neuron index into the network.
double GetLastUpdate () const
It gets the last update time.
double GetPredictedSpike () const
It gets the time of the next predicted spike.
double GetPredictionEnd () const
It gets the time of the end of the next predicted spike.
int GetInputNumber () const
It gets the number of inputs to the current neuron.
int GetOutputNumber () const
It gets the number of output from the current neuron.
float GetStateVarAt (int index) const
It gets the state variable at an specified index.
Interconnection * GetInputConnectionAt (int index) const
It gets the input connection at an specified index.
void AddInputConnection (Interconnection *Connection)
It adds an input connection to the neuron.
bool IsInputConnected () const
It checks if the neuron has some input connection.
Interconnection * GetOutputConnectionAt (int index) const
It gets the output connection at an specified index.
void AddOutputConnection (Interconnection *Connection)
It adds an output connection to the neuron.
bool IsOutputConnected () const
It checks if the neuron has some output connection.
bool IsMonitored () const
It checks if the neuron is monitored.
bool IsOutput () const
It checks if the neuron is output.
NeuronType * GetNeuronType () const
It gets the neuron type.
Private Member Functions
void NeuronUpdate (double ElapsedTime)
It updates the neuron state.
void SynapsisEffect (Interconnection *inter)
It calculates the effect of an input spike in the neuron.
double FiringPrediction ()
It calculates the spike firing time.
double FiringEndPrediction ()
It calculates the time when the next spike will finish.
Private Attributes
NeuronType * type
Neuron associated model.
long int index
Neuron index into the network neurons.
float statevars [MAXSTATEVARS]
Neuron state variables.
double lastupdate
Last update time.
double predictedspike
double predictionend
vector
< Interconnection * > OutputConnections
vector
< Interconnection * > InputConnections
bool monitored
bool isOutput
Detailed Description
Spiking neuron.
This class abstract the behaviour of a neuron in a spiking neural network. It includes network characteristics as index in the network or input and output connections and spiking characteristics as the neural model, the current state, the last updated time, or the spike prediction.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 42 of file Neuron.h.
Constructor & Destructor Documentation
Neuron::Neuron ()
Default constructor without parameters.
It generates a new default neuron object without input connections, output connections or neuron model. The neuron will be initialized with the default values.
Definition at line 10 of file Neuron.cpp.
Neuron::Neuron (int NewIndex, NeuronType * Type, bool Monitored, bool IsOutput)
Neuron constructor with parameters.
It generates a new neuron with neuron model Type and neuron index NewIndex. Moreover, it initializes the neuron variables with the model initial values.
Parameters:
NewIndex The neuron index into the network order.
Type The neuron type. It can't be null.
Monitored If true, the neuron activity will be registered.
IsOutput If true, the neuron activity will be send to output driver
See also:
InitNeuron()
Definition at line 13 of file Neuron.cpp.
References InitNeuron().
Member Function Documentation
void Neuron::NeuronUpdate (double ElapsedTime) [private]
It updates the neuron state.
It updates the neuron state variables for the elapsed time
Parameters:
ElapsedTime Elapsed time since the time of the last update.
Definition at line 46 of file Neuron.cpp.
References NeuronType::GetStateVarAt(), NeuronType::GetStateVarsNumber(), NeuronType::GetStateVarTableAt(), NeuronType::GetTimeDependentStateVarsNumber(), MAXSTATEVARS, statevars, NeuronType::TableAccess(), and type.
Referenced by GenerateAutoActivity(), ProcessInputActivity(), and ProcessInputSynapticActivity().
void Neuron::SynapsisEffect (Interconnection * inter) [private]
It calculates the effect of an input spike in the neuron.
It calculates the effect of an input spike belong the interconnection inter. It updates the neuron membrane potential according the connection synaptic weight.
Parameters:
inter Input connection where the spike fire.
Precondition:
inter must be an input connection to the current neuron.
Definition at line 66 of file Neuron.cpp.
References NeuronType::GetSynapticVarsAt(), Interconnection::GetType(), Interconnection::GetWeight(), statevars, type, and WEIGHTSCALE.
Referenced by ProcessInputSynapticActivity().
double Neuron::FiringPrediction () [private]
It calculates the spike firing time.
It calculates the time to the next spike fire with the current neural state. It queries the firing prediction table.
Returns:
The time to the next fire. -1.0 if spike won't be fired with the current state.
Definition at line 80 of file Neuron.cpp.
References NeuronType::GetFiringTable(), statevars, NeuronType::TableAccess(), and type.
Referenced by GenerateAutoActivity(), GenerateInputActivity(), and InitNeuronPrediction().
double Neuron::FiringEndPrediction () [private]
It calculates the time when the next spike will finish.
It calculates the time to the next spike finish with the current neural state. It queries the firing end prediction table.
Returns:
The time to the next fire ends.
Definition at line 72 of file Neuron.cpp.
References NeuronType::GetFiringEndTable(), statevars, NeuronType::TableAccess(), and type.
Referenced by ProcessInputActivity().
void Neuron::InitNeuron (int NewIndex, NeuronType * Type, bool Monitored, bool IsOutput)
It initializes the neuron values.
It initializes a neuron object with neuron model Type and neuron index NewIndex. Moreover, it initializes the neuron variables with the model initial values.
Parameters:
NewIndex The neuron index into the network order.
Type The neuron type. It can't be null.
Monitored If true, the neuron activity will be registered.
IsOutput If true, the neuron activity will be send to output driver
Definition at line 17 of file Neuron.cpp.
References NeuronType::GetInitValueAt(), NeuronType::GetStateVarsNumber(), index, isOutput, lastupdate, monitored, NOPREDICTION, predictedspike, predictionend, statevars, and type.
Referenced by Network::LoadNet(), and Neuron().
void Neuron::InitNeuronPrediction (EventQueue * eventQueue)
It generates the initial neuron activity.
It generates the initial events in the neuron. It gets the time when the first spike will be fired (without external activity) and inserts a new event in SpikeQueue.
Parameters:
eventQueue The event queue where the event will be inserted.
Definition at line 35 of file Neuron.cpp.
References FiringPrediction(), EventQueue::InsertEvent(), lastupdate, NOPREDICTION, predictedspike, Spike::SetSource(), and Event::SetTime().
void Neuron::GenerateAutoActivity (EventQueue * eventQueue)
It generates the next spike in the neuron without input activity.
It checks if the neuron will fire a new spike without input activity and inserts its in the spike queue.
Note:
It's only necessary when the neuron can fire periodically without input activity.
Parameters:
eventQueue The event queue where the event will be inserted.
Definition at line 88 of file Neuron.cpp.
References FiringPrediction(), EventQueue::InsertEvent(), lastupdate, NeuronUpdate(), NOPREDICTION, predictedspike, and predictionend.
Referenced by GenerateInputActivity(), and InternalSpike::ProcessEvent().
void Neuron::ProcessInputActivity (InternalSpike * InputSpike)
It updates the neural state after an input spike.
It updates the neural state variables after an input spike.
Parameters:
InputSpike Input spike who arrives the current object.
Precondition:
InputSpike.GetSource() must be this.
Note:
It's only necessary when InputSpike.GetTarget()==-2
Definition at line 99 of file Neuron.cpp.
References DEF_REF_PERIOD, FiringEndPrediction(), Event::GetTime(), lastupdate, NeuronUpdate(), NOPREDICTION, and predictionend.
Referenced by InternalSpike::ProcessEvent().
void Neuron::ProcessInputSynapticActivity (PropagatedSpike * InputSpike)
It updates the neural state after a synaptic input spike (target neuron).
It updates the neural state variables of a target neuron after an spike.
Parameters:
InputSpike Input spike who arrives the current object.
Precondition:
InputSpike.GetTarget() must be greater or equal than 0.
Definition at line 112 of file Neuron.cpp.
References GetOutputConnectionAt(), Spike::GetSource(), PropagatedSpike::GetTarget(), Event::GetTime(), lastupdate, NeuronUpdate(), and SynapsisEffect().
Referenced by PropagatedSpike::ProcessEvent().
void Neuron::GenerateOutputActivity (Spike * InputSpike, EventQueue * eventQueue)
It generates the first output spike.
It produces the first output spike in the first output connection of the current neuron. This spike will be propagated.
Parameters:
InputSpike Current spike which generates the activity.
eventQueue The event queue where the event will be inserted.
Note:
This function will be called when we process a spike with target lower than 0.
Definition at line 119 of file Neuron.cpp.
References Event::GetTime(), EventQueue::InsertEvent(), and OutputConnections.
Referenced by InternalSpike::ProcessEvent(), and InputSpike::ProcessEvent().
void Neuron::PropagateOutputSpike (PropagatedSpike * LastSpike, EventQueue * eventQueue)
It propagates an output spike.
It produces the next output spike in the next output connection.
Parameters:
LastSpike The last processed spike.
Precondition:
LastSpike.GetSource() must be equal to this.
Parameters:
eventQueue The event queue where the event will be inserted.
Note:
This function will be called when we process a spike with target greater or equal than 0.
Definition at line 126 of file Neuron.cpp.
References Interconnection::GetDelay(), PropagatedSpike::GetTarget(), Event::GetTime(), EventQueue::InsertEvent(), and OutputConnections.
Referenced by PropagatedSpike::ProcessEvent().
void Neuron::GenerateInputActivity (EventQueue * eventQueue)
It checks if a new spike will be fired.
It updates the neuron next spike time and inserts the spike in the event queue. Moreover, it checks if the neuron generates autoactivity.
Parameters:
eventQueue The event queue where the event will be inserted.
Note:
This function will be called after we process a propagated spike.
Definition at line 134 of file Neuron.cpp.
References FiringPrediction(), GenerateAutoActivity(), EventQueue::InsertEvent(), lastupdate, NOPREDICTION, and predictedspike.
Referenced by PropagatedSpike::ProcessEvent().
long int Neuron::GetIndex () const
It gets the neuron index into the network.
It returns the saved neuron index into the network's neurons.
Returns:
The neuron index.
Definition at line 147 of file Neuron.cpp.
References index.
Referenced by Network::GetNetInfo().
double Neuron::GetLastUpdate () const
It gets the last update time.
It returns the last update time in that neuron.
Returns:
The last update time.
Definition at line 151 of file Neuron.cpp.
References lastupdate.
Referenced by Network::GetNetInfo(), InternalSpike::ProcessEvent(), and InputSpike::ProcessEvent().
double Neuron::GetPredictedSpike () const
It gets the time of the next predicted spike.
It returns the time of the next predicted spike.
Returns:
The time of the next predicted spike.
Definition at line 159 of file Neuron.cpp.
References predictedspike.
Referenced by Network::GetNetInfo(), and InternalSpike::ProcessEvent().
double Neuron::GetPredictionEnd () const
It gets the time of the end of the next predicted spike.
It returns the time of the end of the next predicted spike.
Returns:
The time of the end of the next predicted spike.
Definition at line 167 of file Neuron.cpp.
References predictionend.
int Neuron::GetInputNumber () const
It gets the number of inputs to the current neuron.
It returns the number of input connections to the current neuron.
Returns:
The number of input connections to the current neuron.
Definition at line 175 of file Neuron.cpp.
References InputConnections.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), and AdditiveWeightChange::ApplyWeightChange().
int Neuron::GetOutputNumber () const
It gets the number of output from the current neuron.
It returns the number of output connections from the current neuron.
Returns:
The number of output connections from the current neuron.
Definition at line 179 of file Neuron.cpp.
References OutputConnections.
Referenced by Network::GetNetInfo().
float Neuron::GetStateVarAt (int index) const
It gets the state variable at an specified index.
It returns the state variable at index index.
Parameters:
index The index of the state variable what we want to get.
Returns:
The state variable of index index.
Definition at line 183 of file Neuron.cpp.
References statevars.
Referenced by Network::GetNetInfo(), PropagatedSpike::ProcessEvent(), InternalSpike::ProcessEvent(), and InputSpike::ProcessEvent().
Interconnection * Neuron::GetInputConnectionAt (int index) const
It gets the input connection at an specified index.
It returns the input connection at index index.
Parameters:
index The index of the input connection what we want to get.
Returns:
The input connection of index index.
Definition at line 187 of file Neuron.cpp.
References InputConnections.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), and AdditiveWeightChange::ApplyWeightChange().
void Neuron::AddInputConnection (Interconnection * Connection)
It adds an input connection to the neuron.
It adds the parameter connection as an input connection to the neuron.
Parameters:
Connection The input connection to add.
Definition at line 191 of file Neuron.cpp.
References InputConnections.
Referenced by Network::FindInConnections().
bool Neuron::IsInputConnected () const
It checks if the neuron has some input connection.
It checks if the number of input connections is greater than 0.
Returns:
True if the neuron has some input connection. False in other case.
Definition at line 195 of file Neuron.cpp.
References InputConnections.
Interconnection * Neuron::GetOutputConnectionAt (int index) const
It gets the output connection at an specified index.
It returns the output connection at index index.
Parameters:
index The index of the output connection what we want to get.
Returns:
The output connection of index index.
Definition at line 199 of file Neuron.cpp.
References OutputConnections.
Referenced by PropagatedSpike::ProcessEvent(), and ProcessInputSynapticActivity().
void Neuron::AddOutputConnection (Interconnection * Connection)
It adds an output connection to the neuron.
It adds the parameter connection as an output connection to the neuron.
Parameters:
Connection The output connection to add.
Definition at line 203 of file Neuron.cpp.
References OutputConnections.
Referenced by Network::FindOutConnections().
bool Neuron::IsOutputConnected () const
It checks if the neuron has some output connection.
It checks if the number of output connections is greater than 0.
Returns:
True if the neuron has some output connection. False in other case.
Definition at line 207 of file Neuron.cpp.
References OutputConnections.
bool Neuron::IsMonitored () const
It checks if the neuron is monitored.
It checks if the neuron activity will be registered.
Returns:
True if the neuron is monitored. False in other case.
Definition at line 211 of file Neuron.cpp.
References monitored.
Referenced by Network::GetNetInfo(), Simulation::WritePotential(), and Simulation::WriteSpike().
bool Neuron::IsOutput () const
It checks if the neuron is output.
It checks if the neuron activity is output.
Returns:
True if the neuron is output. False in other case.
Definition at line 215 of file Neuron.cpp.
References isOutput.
Referenced by Simulation::WritePotential(), and Simulation::WriteSpike().
NeuronType * Neuron::GetNeuronType () const
It gets the neuron type.
It returns the neuron type of the current object.
Returns:
The neuron type of the current object.
Definition at line 219 of file Neuron.cpp.
References type.
Referenced by Network::GetNetInfo().
Member Data Documentation
NeuronType* Neuron::type [private]
Neuron associated model.
Definition at line 48 of file Neuron.h.
Referenced by FiringEndPrediction(), FiringPrediction(), GetNeuronType(), InitNeuron(), NeuronUpdate(), and SynapsisEffect().
long int Neuron::index [private]
Neuron index into the network neurons.
Definition at line 53 of file Neuron.h.
Referenced by GetIndex(), and InitNeuron().
float Neuron::statevars[MAXSTATEVARS] [private]
Neuron state variables.
Definition at line 58 of file Neuron.h.
Referenced by FiringEndPrediction(), FiringPrediction(), GetStateVarAt(), InitNeuron(), NeuronUpdate(), and SynapsisEffect().
double Neuron::lastupdate [private]
Last update time.
Definition at line 63 of file Neuron.h.
Referenced by GenerateAutoActivity(), GenerateInputActivity(), GetLastUpdate(), InitNeuron(), InitNeuronPrediction(), ProcessInputActivity(), and ProcessInputSynapticActivity().
double Neuron::predictedspike [private]
Next spike predicted time.
Definition at line 68 of file Neuron.h.
Referenced by GenerateAutoActivity(), GenerateInputActivity(), GetPredictedSpike(), InitNeuron(), and InitNeuronPrediction().
double Neuron::predictionend [private]
End of the event prediction.
Definition at line 73 of file Neuron.h.
Referenced by GenerateAutoActivity(), GetPredictionEnd(), InitNeuron(), and ProcessInputActivity().
vector<Interconnection*> Neuron::OutputConnections [private]
Output connections.
Definition at line 79 of file Neuron.h.
Referenced by AddOutputConnection(), GenerateOutputActivity(), GetOutputConnectionAt(), GetOutputNumber(), IsOutputConnected(), and PropagateOutputSpike().
vector<Interconnection*> Neuron::InputConnections [private]
Input connections.
Definition at line 84 of file Neuron.h.
Referenced by AddInputConnection(), GetInputConnectionAt(), GetInputNumber(), and IsInputConnected().
bool Neuron::monitored [private]
It tells if neuron activity will be registered.
Definition at line 89 of file Neuron.h.
Referenced by InitNeuron(), and IsMonitored().
bool Neuron::isOutput [private]
It tells if neuron is output neuron
Definition at line 94 of file Neuron.h.
Referenced by InitNeuron(), and IsOutput().
The documentation for this class was generated from the following files:
src/spike/include/Neuron.h
src/spike/Neuron.cpp