EDLUTKernel: Spike Class Reference
Spike Class Reference
Neural network spike.
#include <Spike.h>
Public Member Functions
Spike ()
Default constructor.
Spike (double NewTime, Neuron *NewSource)
Constructor with parameters.
~Spike ()
Class destructor.
Neuron * GetSource () const
It gets the spike source neuron.
void SetSource (Neuron *NewSource)
It sets the spike source neuron.
virtual void ProcessEvent (Simulation *CurrentSimulation)=0
It process an event in the simulation.
Protected Attributes
Neuron * source
Friends
ostream & operator<< (ostream &out, Spike *spike)
It prints an spike in the output.
Detailed Description
Neural network spike.
This class abstract the concept of spike. A spike is an event which generates a neuron state update.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 35 of file Spike.h.
Constructor & Destructor Documentation
Spike::Spike ()
Default constructor.
It creates and initializes a new spike object.
Definition at line 5 of file Spike.cpp.
Spike::Spike (double NewTime, Neuron * NewSource)
Constructor with parameters.
It creates and initializes a new spike with the parameters.
Parameters:
NewTime Time of the new spike.
NewSource Source neuron of the spike.
Definition at line 8 of file Spike.cpp.
Spike::~Spike ()
Class destructor.
It destroies an object of this class.
Definition at line 11 of file Spike.cpp.
Member Function Documentation
Neuron * Spike::GetSource () const
It gets the spike source neuron.
It gets the spike source neuron.
Returns:
The spike source neuron.
Definition at line 14 of file Spike.cpp.
References source.
Referenced by InternalSpike::ProcessEvent(), InputSpike::ProcessEvent(), Neuron::ProcessInputSynapticActivity(), and Simulation::WriteSpike().
void Spike::SetSource (Neuron * NewSource)
It sets the spike source neuron.
It sets the spike source neuron.
Parameters:
NewSource The new spike source neuron.
Definition at line 18 of file Spike.cpp.
References source.
Referenced by Neuron::InitNeuronPrediction().
virtual void Spike::ProcessEvent (Simulation * CurrentSimulation) [pure virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implements Event.
Implemented in InputSpike, InternalSpike, and PropagatedSpike.
Friends And Related Function Documentation
ostream& operator<< (ostream & out, Spike * spike) [friend]
It prints an spike in the output.
It prints an spike in the output.
Parameters:
out The output stream.
spike The spike for printing.
Member Data Documentation
Neuron* Spike::source [protected]
Source neuron of the spike.
Definition at line 41 of file Spike.h.
Referenced by GetSource(), PropagatedSpike::ProcessEvent(), InternalSpike::ProcessEvent(), InputSpike::ProcessEvent(), and SetSource().
The documentation for this class was generated from the following files:
src/spike/include/Spike.h
src/spike/Spike.cpp