EDLUTKernel: Event Class Reference
Event Class Reference
Simulation abstract event.
#include <Event.h>
Public Member Functions
Event ()
Default constructor.
Event (double NewTime)
Constructor with parameters.
virtual ~Event ()
Class destructor.
double GetTime () const
It gets the event time.
void SetTime (double NewTime)
It sets the event time.
virtual void ProcessEvent (Simulation *CurrentSimulation)=0
It process an event in the simulation.
Protected Attributes
double time
Detailed Description
Simulation abstract event.
This class abstract the concept of event.
Author:
Jesus Garrido
Date:
November 2008
Definition at line 29 of file Event.h.
Constructor & Destructor Documentation
Event::Event ()
Default constructor.
It creates and initializes a new event object.
Definition at line 5 of file Event.cpp.
Event::Event (double NewTime)
Constructor with parameters.
It creates and initializes a new event with the parameters.
Parameters:
NewTime Time of the new event.
Definition at line 8 of file Event.cpp.
Event::~Event () [virtual]
Class destructor.
It destroies an object of this class.
Definition at line 11 of file Event.cpp.
Member Function Documentation
double Event::GetTime () const
It gets the event time.
It gets the event time.
Returns:
The event time.
Definition at line 14 of file Event.cpp.
References time.
Referenced by Neuron::GenerateOutputActivity(), Neuron::ProcessInputActivity(), Neuron::ProcessInputSynapticActivity(), Neuron::PropagateOutputSpike(), and Simulation::RunSimulation().
void Event::SetTime (double NewTime)
It sets the event time.
It sets the event time.
Parameters:
NewTime The new event time.
Definition at line 18 of file Event.cpp.
References time.
Referenced by Neuron::InitNeuronPrediction(), and EventQueue::RemoveEvent().
virtual void Event::ProcessEvent (Simulation * CurrentSimulation) [pure virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implemented in CommunicationEvent, EndSimulationEvent, SaveWeightsEvent, InputSpike, InternalSpike, PropagatedSpike, and Spike.
Referenced by Simulation::RunSimulation().
Member Data Documentation
double Event::time [protected]
Time when the event happens.
Definition at line 35 of file Event.h.
Referenced by GetTime(), InternalSpike::ProcessEvent(), and SetTime().
The documentation for this class was generated from the following files:
src/simulation/include/Event.h
src/simulation/Event.cpp