EDLUTKernel: NeuronModelTable Class Reference
NeuronModelTable Class Reference
Precalculated table of a neuron model.
#include <NeuronModelTable.h>
Public Member Functions
NeuronModelTable ()
Default constructor.
~NeuronModelTable ()
Class destructor.
void LoadTable (FILE *fd) throw (EDLUTException)
It loads a neuron model table.
void LoadTableDescription (FILE *fh, long &Currentline) throw (EDLUTFileException)
It loads the table description from a file.
TableDimension GetDimensionAt (int index) const
It gets a table dimension.
void SetDimensionAt (int index, TableDimension Dimension)
It sets a table dimension.
unsigned long GetDimensionNumber () const
It gets the number of dimensions.
float GetElementAt (int index) const
It gets an element of the table.
void SetElementAt (int index, float Element)
It sets an element of the table.
unsigned long GetElementsNumber () const
It gets the number of elements.
float TableAccess (float *statevars)
It gets the table value.
Private Types
typedef float(NeuronModelTable::* function)(float statevars[MAXSTATEVARS])
Private Member Functions
void GenerateVirtualCoordinates () throw (EDLUTException)
It generates the virtual coordinates of the table.
float TableAccessDirect (float statevars[MAXSTATEVARS])
It gets a table value without interpolation.
float TableAccessInterpBi (float statevars[MAXSTATEVARS])
It gets a table value with bilinear interpolation.
float TableAccessInterpLi (float statevars[MAXSTATEVARS])
It gets a table value with linear interpolation.
float TableAccessInterpLiEx (float statevars[MAXSTATEVARS])
It gets a table value with linear-ex interpolation.
float TableAccessInterp2Li (float statevars[MAXSTATEVARS])
It gets a table value with linear interpolation from 2 different positions.
float TableAccessInterpNLi (float statevars[MAXSTATEVARS])
It gets a table value with linear interpolation from n different positions.
Private Attributes
void * elems
unsigned long ndims
unsigned long nelems
TableDimension dims [MAXSTATEVARS]
int interp
int firstintdim
Classes
class TableDimension
Dimension of a neuron model table.
Detailed Description
Precalculated table of a neuron model.
This class abstract the behaviour of a neuron model table. These tables are used for access to the behaviour of a neuron model. These tables are loaded from a file and externally generated.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 40 of file NeuronModelTable.h.
Member Typedef Documentation
typedef float(NeuronModelTable::* NeuronModelTable::function)(float statevars[MAXSTATEVARS]) [private]
Function used in function arrays.
Definition at line 252 of file NeuronModelTable.h.
Constructor & Destructor Documentation
NeuronModelTable::NeuronModelTable ()
Default constructor.
It creates and initializes a new neuron model table with their default values.
Definition at line 17 of file NeuronModelTable.cpp.
NeuronModelTable::~NeuronModelTable ()
Class destructor.
It destroys an object and frees the used memory.
Definition at line 21 of file NeuronModelTable.cpp.
References elems.
Member Function Documentation
void NeuronModelTable::LoadTable (FILE * fd) throw (EDLUTException)
It loads a neuron model table.
It loads the neuron model table values from the .dat file.
Parameters:
fd Neuron model table file descriptor.
Precondition:
The file descriptor must be where this table starts, so this is thought for loading all tables in order.
Postcondition:
The file descriptor is where this table description ends.
Exceptions:
EDLUTException If something wrong happens.
Definition at line 105 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, GenerateVirtualCoordinates(), ndims, nelems, and NeuronModelTable::TableDimension::size.
Referenced by NeuronType::LoadTables().
void NeuronModelTable::LoadTableDescription (FILE * fh, long & Currentline) throw (EDLUTFileException)
It loads the table description from a file.
It loads the table description from a .cfg file.
Parameters:
fh The file descriptor of the neuron model table description.
Currentline The line in the file where we are reading (for error description reasons).
Precondition:
The file descriptor must be where this table description starts, so this is thought for loading all tables in order.
Postcondition:
The file descriptor is where this table description ends.
Currentline is modified with the next line in the file.
Definition at line 174 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, firstintdim, NeuronModelTable::TableDimension::interp, interp, NeuronModelTable::TableDimension::nextintdim, skip_comments(), NeuronModelTable::TableDimension::vindex, and NeuronModelTable::TableDimension::voffset.
Referenced by NeuronType::LoadNeuronType().
NeuronModelTable::TableDimension NeuronModelTable::GetDimensionAt (int index) const
It gets a table dimension.
It gets a table dimension of the neuron model table.
Parameters:
index The index of the dimension.
Returns:
The indexth table dimension.
Definition at line 216 of file NeuronModelTable.cpp.
References dims.
Referenced by NeuronType::LoadNeuronType().
void NeuronModelTable::SetDimensionAt (int index, NeuronModelTable::TableDimension Dimension)
It sets a table dimension.
It sets a table dimension of the neuron model table.
Parameters:
index The index of the dimension to set.
Dimension The new dimension of the neuron model table.
Definition at line 220 of file NeuronModelTable.cpp.
References dims.
unsigned long NeuronModelTable::GetDimensionNumber () const
It gets the number of dimensions.
It gets the number of table dimensions.
Returns:
The number of table dimensions.
Definition at line 224 of file NeuronModelTable.cpp.
References ndims.
Referenced by NeuronType::LoadNeuronType(), and NeuronType::LoadTables().
float NeuronModelTable::GetElementAt (int index) const
It gets an element of the table.
It gets an concret element of the table.
Parameters:
index The index of the element to get.
Returns:
The value of the indexth element.
Definition at line 228 of file NeuronModelTable.cpp.
void NeuronModelTable::SetElementAt (int index, float Element)
It sets an element of the table.
It sets an concret element of the table.
Parameters:
index The index of the element to set.
Element The new value of the element.
Definition at line 232 of file NeuronModelTable.cpp.
unsigned long NeuronModelTable::GetElementsNumber () const
It gets the number of elements.
It gets the number of elements in the table.
Returns:
The number of elements in the table.
Definition at line 236 of file NeuronModelTable.cpp.
References nelems.
float NeuronModelTable::TableAccess (float * statevars)
It gets the table value.
It gets the table value with concrete state variables and the current interpolation method.
Parameters:
statevars The current state variables of the neuron.
Returns:
The value of the table (with or without interpolation).
Definition at line 562 of file NeuronModelTable.cpp.
References TableAccessDirect(), TableAccessInterp2Li(), TableAccessInterpBi(), TableAccessInterpLi(), TableAccessInterpLiEx(), and TableAccessInterpNLi().
Referenced by NeuronType::TableAccess().
void NeuronModelTable::GenerateVirtualCoordinates () throw (EDLUTException) [private]
It generates the virtual coordinates of the table.
This funcion generates the virtual coordinates of the table. That is necessary for correctly accessing to the interpolated dimensions.
Exceptions:
EDLUTException If something wrong happens.
Definition at line 25 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, ndims, NeuronModelTable::TableDimension::size, NeuronModelTable::TableDimension::vfirst, NeuronModelTable::TableDimension::vindex, NeuronModelTable::TableDimension::voffset, and NeuronModelTable::TableDimension::vscale.
Referenced by LoadTable().
float NeuronModelTable::TableAccessDirect (float statevars[MAXSTATEVARS]) [private]
It gets a table value without interpolation.
It gets a table value without interpolation with concrete state variables.
Parameters:
statevars State variables of the neuron.
Returns:
The table value with that state.
Definition at line 248 of file NeuronModelTable.cpp.
References dims, elems, ndims, NeuronModelTable::TableDimension::statevar, and table_indcomp2.
Referenced by TableAccess().
float NeuronModelTable::TableAccessInterpBi (float statevars[MAXSTATEVARS]) [private]
It gets a table value with bilinear interpolation.
It gets a table value with bilinear interpolation with concrete state variables.
Parameters:
statevars State variables of the neuron.
Returns:
The table value with that state.
Definition at line 268 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, firstintdim, NeuronModelTable::TableDimension::interp, last_coord, ndims, NeuronModelTable::TableDimension::nextintdim, NeuronModelTable::TableDimension::size, NeuronModelTable::TableDimension::statevar, table_ind_int, and table_indcomp2.
Referenced by TableAccess().
float NeuronModelTable::TableAccessInterpLi (float statevars[MAXSTATEVARS]) [private]
It gets a table value with linear interpolation.
It gets a table value with linear interpolation with concrete state variables.
Parameters:
statevars State variables of the neuron.
Returns:
The table value with that state.
Definition at line 327 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, firstintdim, NeuronModelTable::TableDimension::interp, last_coord, ndims, NeuronModelTable::TableDimension::nextintdim, NeuronModelTable::TableDimension::size, NeuronModelTable::TableDimension::statevar, table_ind_int, and table_indcomp2.
Referenced by TableAccess().
float NeuronModelTable::TableAccessInterpLiEx (float statevars[MAXSTATEVARS]) [private]
It gets a table value with linear-ex interpolation.
It gets a table value with linear-ex interpolation with concrete state variables.
Parameters:
statevars State variables of the neuron.
Returns:
The table value with that state.
Definition at line 380 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, firstintdim, NeuronModelTable::TableDimension::interp, last_coord, ndims, NeuronModelTable::TableDimension::nextintdim, NeuronModelTable::TableDimension::size, NeuronModelTable::TableDimension::statevar, table_ind_int, and table_indcomp2.
Referenced by TableAccess().
float NeuronModelTable::TableAccessInterp2Li (float statevars[MAXSTATEVARS]) [private]
It gets a table value with linear interpolation from 2 different positions.
It gets a table value with linear interpolation from 2 different positions with concrete state variables.
Parameters:
statevars State variables of the neuron.
Returns:
The table value with that state.
Definition at line 432 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, firstintdim, NeuronModelTable::TableDimension::interp, last_coord, ndims, NeuronModelTable::TableDimension::nextintdim, NeuronModelTable::TableDimension::size, NeuronModelTable::TableDimension::statevar, table_ind_int, and table_indcomp2.
Referenced by TableAccess().
float NeuronModelTable::TableAccessInterpNLi (float statevars[MAXSTATEVARS]) [private]
It gets a table value with linear interpolation from n different positions.
It gets a table value with linear interpolation from n different positions with concrete state variables.
Parameters:
statevars State variables of the neuron.
Returns:
The table value with that state.
Definition at line 500 of file NeuronModelTable.cpp.
References NeuronModelTable::TableDimension::coord, dims, elems, firstintdim, NeuronModelTable::TableDimension::interp, last_coord, ndims, NeuronModelTable::TableDimension::nextintdim, NeuronModelTable::TableDimension::size, NeuronModelTable::TableDimension::statevar, table_ind_int, and table_indcomp2.
Referenced by TableAccess().
Member Data Documentation
void* NeuronModelTable::elems [private]
Elements of the table.
Definition at line 257 of file NeuronModelTable.h.
Referenced by LoadTable(), LoadTableDescription(), TableAccessDirect(), TableAccessInterp2Li(), TableAccessInterpBi(), TableAccessInterpLi(), TableAccessInterpLiEx(), TableAccessInterpNLi(), and ~NeuronModelTable().
unsigned long NeuronModelTable::ndims [private]
Number of dimensions.
Definition at line 262 of file NeuronModelTable.h.
Referenced by GenerateVirtualCoordinates(), GetDimensionNumber(), LoadTable(), TableAccessDirect(), TableAccessInterp2Li(), TableAccessInterpBi(), TableAccessInterpLi(), TableAccessInterpLiEx(), and TableAccessInterpNLi().
unsigned long NeuronModelTable::nelems [private]
Number of elements.
Definition at line 267 of file NeuronModelTable.h.
Referenced by GetElementsNumber(), and LoadTable().
TableDimension NeuronModelTable::dims[MAXSTATEVARS] [private]
Table dimensions.
Definition at line 272 of file NeuronModelTable.h.
Referenced by GenerateVirtualCoordinates(), GetDimensionAt(), LoadTable(), LoadTableDescription(), SetDimensionAt(), TableAccessDirect(), TableAccessInterp2Li(), TableAccessInterpBi(), TableAccessInterpLi(), TableAccessInterpLiEx(), and TableAccessInterpNLi().
int NeuronModelTable::interp [private]
Interpolation of some dimension.
Definition at line 277 of file NeuronModelTable.h.
Referenced by LoadTableDescription().
int NeuronModelTable::firstintdim [private]
The first interpolated dimension.
Definition at line 282 of file NeuronModelTable.h.
Referenced by LoadTableDescription(), TableAccessInterp2Li(), TableAccessInterpBi(), TableAccessInterpLi(), TableAccessInterpLiEx(), and TableAccessInterpNLi().
The documentation for this class was generated from the following files:
src/spike/include/NeuronModelTable.h
src/spike/NeuronModelTable.cpp