EDLUTKernel: src/spike/include/EDLUTException.h File Reference
src/spike/include/EDLUTException.h File Reference
#include <cstdlib>
#include <cstdio>
#include <iostream>
Classes
class EDLUTException
Exception in the simulation process.
Functions
ostream & operator<< (ostream &out, EDLUTException Exception)
It prints the error message of this exception.
Detailed Description
Author:
Jesus Garrido
Richard Carrido
Date:
August 2008
This file declares a class which abstracts an exception in the EDLUT simulation process.
Definition in file EDLUTException.h.
Function Documentation
ostream& operator<< (ostream & out, EDLUTException Exception)
It prints the error message of this exception.
It prints the error message of this exception.
Parameters:
out The output stream where the message is printed.
Exception The exception to be printed.
Returns:
The output stream.
Definition at line 143 of file EDLUTException.cpp.
References EDLUTException::GetErrorMsg(), EDLUTException::GetErrorNum(), EDLUTException::GetRepairMsg(), and EDLUTException::GetTaskMsg().