EDLUTKernel: CommunicationEvent Class Reference
CommunicationEvent Class Reference
Simulation abstract event for the communication time.
#include <CommunicationEvent.h>
Public Member Functions
CommunicationEvent ()
Default constructor.
CommunicationEvent (double NewTime)
Constructor with parameters.
~CommunicationEvent ()
Class destructor.
virtual void ProcessEvent (Simulation *CurrentSimulation)
It process an event in the simulation.
Detailed Description
Simulation abstract event for the communication time.
This class abstract the concept of event for the communication time.
Author:
Jesus Garrido
Date:
November 2008
Definition at line 31 of file CommunicationEvent.h.
Constructor & Destructor Documentation
CommunicationEvent::CommunicationEvent ()
Default constructor.
It creates and initializes a new event object.
Definition at line 6 of file CommunicationEvent.cpp.
Referenced by ProcessEvent().
CommunicationEvent::CommunicationEvent (double NewTime)
Constructor with parameters.
It creates and initializes a new event with the parameters.
Parameters:
NewTime Time of the new event.
Definition at line 9 of file CommunicationEvent.cpp.
CommunicationEvent::~CommunicationEvent ()
Class destructor.
It destroies an object of this class.
Definition at line 12 of file CommunicationEvent.cpp.
Member Function Documentation
void CommunicationEvent::ProcessEvent (Simulation * CurrentSimulation) [virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implements Event.
Definition at line 15 of file CommunicationEvent.cpp.
References CommunicationEvent(), Simulation::GetInput(), Simulation::GetQueue(), Simulation::GetSimulationStep(), EventQueue::InsertEvent(), and Simulation::SendOutput().
The documentation for this class was generated from the following files:
src/simulation/include/CommunicationEvent.h
src/simulation/CommunicationEvent.cpp