EDLUTKernel: CdSocket Class Reference
CdSocket Class Reference
A socket used to communicate with another program.
#include <CdSocket.h>
Public Member Functions
CdSocket (unsigned short status, string server_address, unsigned short tcp_port)
Constructor for which parameters of the tcp connection are stored in an external file.
~CdSocket ()
Default destructor.
int sendBuffer (void *buffer, int buffer_size)
Send a block of data.
int receiveBuffer (void *buffer, int buffer_size)
Receive a block of data.
Protected Member Functions
void initializeSocket ()
Protected Attributes
int socket_fd
string serv_host_addr
unsigned short serv_tcp_port
unsigned short status
int ret_status
Detailed Description
A socket used to communicate with another program.
Author:
Christian Boucheny
Definition at line 37 of file CdSocket.h.
Constructor & Destructor Documentation
CdSocket::CdSocket (unsigned short status, string server_address, unsigned short tcp_port)
Constructor for which parameters of the tcp connection are stored in an external file.
Parameters:
status CLIENT or SERVER
server_address address of the server host
tcp_port tcp_port to connect
Definition at line 14 of file CdSocket.cpp.
References initializeSocket(), serv_host_addr, and serv_tcp_port.
CdSocket::~CdSocket ()
Default destructor.
Definition at line 27 of file CdSocket.cpp.
References closesocket, and socket_fd.
Member Function Documentation
int CdSocket::sendBuffer (void * buffer, int buffer_size) [virtual]
Send a block of data.
Parameters:
buffer data to send. Need a cast to char*
buffer_size size of the packet
Returns:
the error signal
Implements CommunicationDevice.
Definition at line 170 of file CdSocket.cpp.
References socket_fd.
Referenced by TCPIPOutputSpikeDriver::FlushBuffers(), and TCPIPInputOutputSpikeDriver::FlushBuffers().
int CdSocket::receiveBuffer (void * buffer, int buffer_size) [virtual]
Receive a block of data.
Parameters:
buffer data to send
buffer_size size of the packet
Returns:
the error signal
Implements CommunicationDevice.
Definition at line 153 of file CdSocket.cpp.
References ret_status, and socket_fd.
Referenced by TCPIPInputSpikeDriver::LoadInputs(), and TCPIPInputOutputSpikeDriver::LoadInputs().
void CdSocket::initializeSocket () [protected]
initialize the socket connections with parameters defined in constructor
Definition at line 33 of file CdSocket.cpp.
References CLIENT, closesocket, SERVER, and socket_fd.
Referenced by CdSocket().
Member Data Documentation
int CdSocket::socket_fd [protected]
The socket itself
Definition at line 95 of file CdSocket.h.
Referenced by initializeSocket(), receiveBuffer(), sendBuffer(), and ~CdSocket().
string CdSocket::serv_host_addr [protected]
host address of the server
Definition at line 102 of file CdSocket.h.
Referenced by CdSocket().
unsigned short CdSocket::serv_tcp_port [protected]
tcp port of the server
Definition at line 109 of file CdSocket.h.
Referenced by CdSocket().
unsigned short CdSocket::status [protected]
is it a client or server ? 0 = CLIENT / 1 = SERVER
Definition at line 116 of file CdSocket.h.
int CdSocket::ret_status [protected]
return value of called I-O functions
Definition at line 123 of file CdSocket.h.
Referenced by receiveBuffer().
The documentation for this class was generated from the following files:
src/communication/include/CdSocket.h
src/communication/CdSocket.cpp