EDLUTKernel: EventQueue Class Reference
EventQueue Class Reference
Event queue.
#include <EventQueue.h>
Public Member Functions
EventQueue ()
Default constructor.
~EventQueue ()
Object destructor.
long long Size () const
It gets the number of events in the queue.
void InsertEvent (Event *event)
It inserts a spike in the event queue.
Event * RemoveEvent (void)
It removes the first event in the queue.
double FirstEventTime (void) const
It returns the time of the first event.
Private Member Functions
void SwapEvents (int c1, int c2)
Private Attributes
vector< Event * > Events
Detailed Description
Event queue.
This class abstract the behaviour of an sorted by event time queue.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 32 of file EventQueue.h.
Constructor & Destructor Documentation
EventQueue::EventQueue ()
Default constructor.
Default constructor without parameters. It creates a new event queue.
Definition at line 5 of file EventQueue.cpp.
EventQueue::~EventQueue ()
Object destructor.
Default object destructor.
Definition at line 9 of file EventQueue.cpp.
Member Function Documentation
void EventQueue::SwapEvents (int c1, int c2) [inline, private]
It swaps the position of two events.
Definition at line 13 of file EventQueue.cpp.
References Events.
Referenced by InsertEvent(), and RemoveEvent().
long long EventQueue::Size () const
It gets the number of events in the queue.
It gets the number of events in the queue.
Returns:
The number of events in the queue.
Definition at line 30 of file EventQueue.cpp.
References Events.
Referenced by FirstEventTime(), InsertEvent(), RemoveEvent(), and Simulation::RunSimulation().
void EventQueue::InsertEvent (Event * event)
It inserts a spike in the event queue.
It inserts a spike in the event queue.
Parameters:
event The new event to insert in the queue.
Definition at line 20 of file EventQueue.cpp.
References Events, Size(), and SwapEvents().
Referenced by Neuron::GenerateAutoActivity(), Neuron::GenerateInputActivity(), Neuron::GenerateOutputActivity(), Neuron::InitNeuronPrediction(), SaveWeightsEvent::ProcessEvent(), CommunicationEvent::ProcessEvent(), Neuron::PropagateOutputSpike(), and Simulation::RunSimulation().
Event * EventQueue::RemoveEvent (void)
It removes the first event in the queue.
It removes the first event in the queue. It returns the first event sorted by time.
Returns:
The first event sorted by time.
Definition at line 34 of file EventQueue.cpp.
References Events, Event::SetTime(), Size(), and SwapEvents().
Referenced by Simulation::RunSimulation().
double EventQueue::FirstEventTime (void) const
It returns the time of the first event.
It returns the time of the first event.
Returns:
The time of the first event.
Definition at line 64 of file EventQueue.cpp.
References Events, and Size().
Member Data Documentation
vector<Event *> EventQueue::Events [private]
Spikes vector.
Definition at line 38 of file EventQueue.h.
Referenced by FirstEventTime(), InsertEvent(), RemoveEvent(), Size(), and SwapEvents().
The documentation for this class was generated from the following files:
src/simulation/include/EventQueue.h
src/simulation/EventQueue.cpp