EDLUTKernel: NeuronType Class Reference
NeuronType Class Reference
Neuron model.
#include <NeuronType.h>
Public Member Functions
char * GetId ()
It gets the neuron model identificator.
int GetStateVarsNumber () const
It gets the number of state variables.
int GetTimeDependentStateVarsNumber () const
It gets the number of time dependent state variables.
int GetStateVarAt (int index) const
It gets the number of a state variable.
int GetStateVarTableAt (int index) const
It gets the table of a concrete variable.
float GetInitValueAt (int index) const
It gets the initial value of a variable.
int GetFiringTable () const
It gets the index of the firing table.
int GetFiringEndTable () const
It gets the index of the end firing table.
int GetSynapticVarsNumber () const
It gets the number of the synaptic variables.
int GetSynapticVarsAt (int index) const
It gets the number of a synaptic variable.
NeuronModelTable * GetTableAt (int index)
It gets a neuron model table.
int GetTableNumber () const
It gets the number of neuron model tables.
void ClearNeuronType ()
It clears the neuron type for loading a new model.
void LoadNeuronType (char *neutype) throw (EDLUTFileException)
It loads the neuron model description.
void LoadTables () throw (EDLUTException)
It loads the neuron model tables.
float TableAccess (int ntab, float *statevars)
It gets a value from the table.
Private Attributes
char ident [MAXIDSIZE+1]
unsigned int nstatevars
unsigned int ntstatevars
int statevarorder [MAXSTATEVARS]
int statevartables [MAXSTATEVARS]
float initvalues [MAXSTATEVARS]
int firingtable
int firingendtable
unsigned int nsynapticvars
int synapticvars [MAXSTATEVARS]
NeuronModelTable tables [MAXSTATEVARS *2]
unsigned int ntables
Detailed Description
Neuron model.
This class abstract the behaviour of a neuron model of a spiking neural network. It includes the name, the number of variables, the initial values, the neuron model tables...
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 32 of file NeuronType.h.
Member Function Documentation
char * NeuronType::GetId ()
It gets the neuron model identificator.
It gets the neuron model name.
Returns:
The neuron model identificator.
Definition at line 8 of file NeuronType.cpp.
References ident.
Referenced by Network::GetNetInfo(), and Network::LoadNetTypes().
int NeuronType::GetStateVarsNumber () const
It gets the number of state variables.
It gets the number of state variables of the neuron model.
Returns:
The number of state variables.
Definition at line 12 of file NeuronType.cpp.
References nstatevars.
Referenced by Network::GetNetInfo(), Neuron::InitNeuron(), and Neuron::NeuronUpdate().
int NeuronType::GetTimeDependentStateVarsNumber () const
It gets the number of time dependent state variables.
It gets the number of time dependent state variables of the neuron model.
Returns:
The number of time dependent state variables.
Definition at line 16 of file NeuronType.cpp.
References ntstatevars.
Referenced by Neuron::NeuronUpdate().
int NeuronType::GetStateVarAt (int index) const
It gets the number of a state variable.
It gets the number of a state variable from the index.
Parameters:
index The index of the state variable to get.
Returns:
The number of the indexth state variable.
Definition at line 20 of file NeuronType.cpp.
References statevarorder.
Referenced by Neuron::NeuronUpdate().
int NeuronType::GetStateVarTableAt (int index) const
It gets the table of a concrete variable.
It gets the index of the table of the indexth variable.
Parameters:
index The index of the variable.
Returns:
The number of the table with the state variable index.
Definition at line 24 of file NeuronType.cpp.
References statevartables.
Referenced by Neuron::NeuronUpdate().
float NeuronType::GetInitValueAt (int index) const
It gets the initial value of a variable.
It gets the initial value of a concrete state variable.
Parameters:
index The index of the variable to get the initial value.
Returns:
The initial value of the indexth variable.
Definition at line 28 of file NeuronType.cpp.
References initvalues.
Referenced by Neuron::InitNeuron().
int NeuronType::GetFiringTable () const
It gets the index of the firing table.
It gets the index of the firing table.
Returns:
The index of the firing table.
Definition at line 32 of file NeuronType.cpp.
References firingtable.
Referenced by Neuron::FiringPrediction().
int NeuronType::GetFiringEndTable () const
It gets the index of the end firing table.
It gets the index of the end firing table.
Returns:
The index of the end firing table.
Definition at line 36 of file NeuronType.cpp.
References firingendtable.
Referenced by Neuron::FiringEndPrediction().
int NeuronType::GetSynapticVarsNumber () const
It gets the number of the synaptic variables.
It gets the number of the synaptic variables.
Returns:
The number of synaptic variables.
Definition at line 40 of file NeuronType.cpp.
References nsynapticvars.
int NeuronType::GetSynapticVarsAt (int index) const
It gets the number of a synaptic variable.
It gets the number of a synaptic variable from the index.
Parameters:
index The index of the synaptic variable to get.
Returns:
The number of the indexth synaptic variable.
Definition at line 44 of file NeuronType.cpp.
References synapticvars.
Referenced by Neuron::SynapsisEffect().
NeuronModelTable * NeuronType::GetTableAt (int index)
It gets a neuron model table.
It gets a neuron model table from the index.
Parameters:
index The index of the neuron model table to get.
Returns:
The number of the indexth neuron model table.
Definition at line 48 of file NeuronType.cpp.
References tables.
int NeuronType::GetTableNumber () const
It gets the number of neuron model tables.
It gets the number of neuron model tables.
Returns:
The number of neuron model tables.
Definition at line 52 of file NeuronType.cpp.
References ntables.
Referenced by Network::GetNetInfo().
void NeuronType::ClearNeuronType ()
It clears the neuron type for loading a new model.
It clears the neuron type, his identificator, the state variables and the neuron model tables.
Definition at line 56 of file NeuronType.cpp.
References ident, nstatevars, and ntables.
Referenced by Network::LoadNet().
void NeuronType::LoadNeuronType (char * neutype) throw (EDLUTFileException)
It loads the neuron model description.
It loads the neuron type description from the file .cfg.
Parameters:
neutype Name of the neuron type (without file extension).
Exceptions:
EDLUTFileException If something wrong has happened in the file load.
Definition at line 62 of file NeuronType.cpp.
References NeuronModelTable::GetDimensionAt(), NeuronModelTable::GetDimensionNumber(), NeuronModelTable::LoadTableDescription(), MAXIDSIZE, MAXSTATEVARS, nstatevars, nsynapticvars, ntables, ntstatevars, skip_comments(), statevarorder, statevartables, and tables.
Referenced by Network::LoadNetTypes().
void NeuronType::LoadTables () throw (EDLUTException)
It loads the neuron model tables.
It loads the neuron model tables from his .dat associated file.
Precondition:
The neuron type must be previously initialized or loaded
See also:
LoadNeuronType()
Exceptions:
EDLUTException If something wrong has happened in the tables loads.
Definition at line 157 of file NeuronType.cpp.
References NeuronModelTable::GetDimensionNumber(), NeuronModelTable::LoadTable(), MAXIDSIZE, ntables, and tables.
Referenced by Network::LoadNeuronTypeTables().
float NeuronType::TableAccess (int ntab, float * statevars)
It gets a value from the table.
It gets the value associated a the table ntab with the statevars nueral state.
Precondition:
The tables must be previously loaded.
Parameters:
ntab Number of the table to get the value.
statevars State variables values of the neuron.
Definition at line 181 of file NeuronType.cpp.
References NeuronModelTable::TableAccess(), and tables.
Referenced by Neuron::FiringEndPrediction(), Neuron::FiringPrediction(), and Neuron::NeuronUpdate().
Member Data Documentation
char NeuronType::ident[MAXIDSIZE+1] [private]
Neuron model name.
Definition at line 38 of file NeuronType.h.
Referenced by ClearNeuronType(), and GetId().
unsigned int NeuronType::nstatevars [private]
Number of state variables.
Definition at line 43 of file NeuronType.h.
Referenced by ClearNeuronType(), GetStateVarsNumber(), and LoadNeuronType().
unsigned int NeuronType::ntstatevars [private]
Number of time dependent state variables.
Definition at line 48 of file NeuronType.h.
Referenced by GetTimeDependentStateVarsNumber(), and LoadNeuronType().
int NeuronType::statevarorder[MAXSTATEVARS] [private]
Order of the state variables.
Definition at line 53 of file NeuronType.h.
Referenced by GetStateVarAt(), and LoadNeuronType().
int NeuronType::statevartables[MAXSTATEVARS] [private]
Tables of the state variables.
Definition at line 58 of file NeuronType.h.
Referenced by GetStateVarTableAt(), and LoadNeuronType().
float NeuronType::initvalues[MAXSTATEVARS] [private]
Initial values.
Definition at line 63 of file NeuronType.h.
Referenced by GetInitValueAt().
int NeuronType::firingtable [private]
Number of the firing table.
Definition at line 68 of file NeuronType.h.
Referenced by GetFiringTable().
int NeuronType::firingendtable [private]
Number of the firing end table.
Definition at line 73 of file NeuronType.h.
Referenced by GetFiringEndTable().
unsigned int NeuronType::nsynapticvars [private]
Number of synaptic variables.
Definition at line 78 of file NeuronType.h.
Referenced by GetSynapticVarsNumber(), and LoadNeuronType().
int NeuronType::synapticvars[MAXSTATEVARS] [private]
Synaptic variables.
Definition at line 83 of file NeuronType.h.
Referenced by GetSynapticVarsAt().
NeuronModelTable NeuronType::tables[MAXSTATEVARS *2] [private]
Neuron model tables.
Definition at line 88 of file NeuronType.h.
Referenced by GetTableAt(), LoadNeuronType(), LoadTables(), and TableAccess().
unsigned int NeuronType::ntables [private]
Number of neuron model tables.
Definition at line 93 of file NeuronType.h.
Referenced by ClearNeuronType(), GetTableNumber(), LoadNeuronType(), and LoadTables().
The documentation for this class was generated from the following files:
src/spike/include/NeuronType.h
src/spike/NeuronType.cpp