EDLUTKernel: SaveWeightsEvent Class Reference
SaveWeightsEvent Class Reference
Simulation abstract event for the save weights time.
#include <SaveWeightsEvent.h>
Public Member Functions
SaveWeightsEvent ()
Default constructor.
SaveWeightsEvent (double NewTime)
Constructor with parameters.
~SaveWeightsEvent ()
Class destructor.
virtual void ProcessEvent (Simulation *CurrentSimulation)
It process an event in the simulation.
Detailed Description
Simulation abstract event for the save weights time.
This class abstract the concept of event for the save weights time.
Author:
Jesus Garrido
Date:
November 2008
Definition at line 31 of file SaveWeightsEvent.h.
Constructor & Destructor Documentation
SaveWeightsEvent::SaveWeightsEvent ()
Default constructor.
It creates and initializes a new event object.
Definition at line 6 of file SaveWeightsEvent.cpp.
Referenced by ProcessEvent().
SaveWeightsEvent::SaveWeightsEvent (double NewTime)
Constructor with parameters.
It creates and initializes a new event with the parameters.
Parameters:
NewTime Time of the new event.
Definition at line 9 of file SaveWeightsEvent.cpp.
SaveWeightsEvent::~SaveWeightsEvent ()
Class destructor.
It destroies an object of this class.
Definition at line 12 of file SaveWeightsEvent.cpp.
Member Function Documentation
void SaveWeightsEvent::ProcessEvent (Simulation * CurrentSimulation) [virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implements Event.
Definition at line 15 of file SaveWeightsEvent.cpp.
References Simulation::GetQueue(), Simulation::GetSaveStep(), EventQueue::InsertEvent(), Simulation::SaveWeights(), and SaveWeightsEvent().
The documentation for this class was generated from the following files:
src/simulation/include/SaveWeightsEvent.h
src/simulation/SaveWeightsEvent.cpp