EDLUTKernel: src/spike/include/EDLUTFileException.h File Reference
src/spike/include/EDLUTFileException.h File Reference
#include <cstdlib>
#include <cstdio>
#include <iostream>
#include "./EDLUTException.h"
Classes
class EDLUTFileException
Exception reading/writting files.
Functions
ostream & operator<< (ostream &out, EDLUTFileException Exception)
It prints the error message of this exception.
Detailed Description
Author:
Jesus Garrido
Richard Carrido
Date:
August 2008
This file declares a class which abstracts an exception in reading/writting files in the EDLUT simulation process.
Definition in file EDLUTFileException.h.
Function Documentation
ostream& operator<< (ostream & out, EDLUTFileException Exception)
It prints the error message of this exception.
It prints the error message of this exception.
Parameters:
out The output stream where the message is printed.
Exception The exception to be printed.
Returns:
The output stream.
Definition at line 28 of file EDLUTFileException.cpp.
References EDLUTFileException::GetErrorLine(), EDLUTException::GetErrorMsg(), EDLUTException::GetErrorNum(), EDLUTException::GetRepairMsg(), and EDLUTException::GetTaskMsg().