EDLUTKernel: src/simulation/include/Utils.h File Reference
src/simulation/include/Utils.h File Reference
#include <cstdio>
Defines
#define COMMENT_CHAR '/'
Functions
int skip_spaces (FILE *fh, long &Currentline)
It skips the white lines, spaces and tab from the Currentline.
void skip_comments (FILE *fh, long &Currentline)
It skips the comment lines from the Currentline.
Detailed Description
Author:
Jesus Garrido
Richard Carrido
Date:
August 2008
This file declares functions for read and processs files.
Definition in file Utils.h.
Define Documentation
#define COMMENT_CHAR '/'
Definition at line 16 of file Utils.h.
Referenced by skip_comments().
Function Documentation
void skip_comments (FILE * fh, long & Currentline)
It skips the comment lines from the Currentline.
It skips the comment lines from the Currentline in advance.
Parameters:
fh The file handler.
Currentline The currentline where we are readding.
Definition at line 13 of file Utils.cpp.
Referenced by FileInputSpikeDriver::LoadInputs(), Network::LoadNet(), NeuronType::LoadNeuronType(), NeuronModelTable::LoadTableDescription(), and Network::LoadWeights().
int skip_spaces (FILE * fh, long & Currentline)
It skips the white lines, spaces and tab from the Currentline.
It skips the white lines from the Currentline in advance.
Parameters:
fh The file handler.
Currentline The currentline where we are readding.
Returns:
True if white lines have been correctly cleared. False in other case.
Definition at line 4 of file Utils.cpp.
Referenced by skip_comments().