EDLUTKernel: ParamReader Class Reference
ParamReader Class Reference
Class for read input parameters.
#include <ParamReader.h>
Public Member Functions
ParamReader (int ArgNumber, char **Arg) throw (ParameterException, ConnectionException)
Default constructor.
double GetSimulationTime ()
It gets the total simulation time.
double GetSaveWeightStepTime ()
It gets the saving weights step time.
char * GetNetworkFile ()
It gets the network configuration file.
char * GetWeightsFile ()
It gets the weights configuration file.
bool CheckInfo ()
It checks if the -info option is enabled.
double GetSimulationStepTime ()
It gets the simulation step time.
vector
< InputSpikeDriver * > GetInputSpikeDrivers ()
It gets the input drivers.
vector
< OutputSpikeDriver * > GetOutputSpikeDrivers ()
It gets the output drivers.
vector
< OutputSpikeDriver * > GetMonitorDrivers ()
It gets the monitoring drivers.
vector
< OutputWeightDriver * > GetOutputWeightDrivers ()
It gets the output weight drivers.
Private Member Functions
void ParseArguments (int Number, char **Arguments) throw (ParameterException, ConnectionException)
It parses the input arguments.
bool FileExists (string Name)
It tests if a file exists.
Private Attributes
double SimulationTime
char * NetworkFile
char * WeightsFile
double WeightTime
bool NetworkInfo
double SimulationStepTime
vector
< InputSpikeDriver * > InputDrivers
vector
< OutputSpikeDriver * > OutputDrivers
vector
< OutputSpikeDriver * > MonitorDrivers
vector
< OutputWeightDriver * > OutputWeightDrivers
Detailed Description
Class for read input parameters.
This class abstract methods for get the input parameters in the simulation.
Note:
Obligatory parameters: -time Simulation_Time(in_seconds) It sets the total simulation time. -nf Network_File It sets the network description file. -wf Weights_File It sets the weights file.
parameters: -info It shows the network information. -log File_Name It saves the monitored cells activity in file File_Name. -sf File_Name It saves the final weights in file File_Name. -wt Save_Weight_Step It sets the step time between weights saving. -st Step_Time(in_seconds) It sets the step time in simulation. -if Input_File It adds the Input_File file in the input sources of the simulation. -of Output_File It adds the Output_File file in the output targets of the simulation. -ic IPAddress:Port Server|Client It adds the connection as a server or a client in the specified direction in the input sources of the simulation. -oc IPAddress:Port Server|Client It adds the connection as a server or a client in the specified direction in the output targets of the simulation. -ioc IPAddress:Port Server|Client It adds the connection as a server or a client in the specified direction in the input sources and in the output targets.
Author:
Jesus Garrido
Date:
September 2008
Definition at line 57 of file ParamReader.h.
Constructor & Destructor Documentation
ParamReader::ParamReader (int ArgNumber, char ** Arg) throw (ParameterException, ConnectionException)
Default constructor.
It creates a new object with the arguments in the parameters.
Parameters:
ArgNumber Number of arguments in Arg.
Arg Arguments of the simulation.
Exceptions:
ParameterException When something wrong happens in the parser proccess.
Definition at line 247 of file ParamReader.cpp.
References ParseArguments().
Member Function Documentation
void ParamReader::ParseArguments (int Number, char ** Arguments) throw (ParameterException, ConnectionException) [private]
It parses the input arguments.
It parses the input arguments and gets the simulation configuration.
Parameters:
Number Number of arguments in Arguments.
Arguments Arguments to be parsed.
Exceptions:
ParameterException When something wrong happens in the parser proccess.
Definition at line 20 of file ParamReader.cpp.
Referenced by ParamReader().
bool ParamReader::FileExists (string Name) [private]
It tests if a file exists.
It tests if a file exists and if we can read it.
Parameters:
Name The file name.
Returns:
True if the file exists and we can read it. False in other case.
Definition at line 236 of file ParamReader.cpp.
double ParamReader::GetSimulationTime ()
It gets the total simulation time.
It gets the total simulation time. The argument indicator for simulation time is -time, so it searchs -time and returns the value as a float.
Returns:
The total simulation time. -1 if the parameter isn't used.
Definition at line 252 of file ParamReader.cpp.
References SimulationTime.
Referenced by main().
double ParamReader::GetSaveWeightStepTime ()
It gets the saving weights step time.
It gets the saving weights step time. The argument indicator for saving weights step time is -wt, so it searchs -wt and returns the value as a float.
Returns:
The saving weights step time. -1 if the parameter isn't used.
Definition at line 256 of file ParamReader.cpp.
References WeightTime.
Referenced by main().
char * ParamReader::GetNetworkFile ()
It gets the network configuration file.
It gets the network configuration file. The argument indicator for network configuration file is -nf, so it searchs -nf and returns the file name.
Returns:
The network configuration file name. NULL if network file isn't introduced.
Definition at line 260 of file ParamReader.cpp.
References NetworkFile.
Referenced by main().
char * ParamReader::GetWeightsFile ()
It gets the weights configuration file.
It gets the weights configuration file. The argument indicator for weights configuration file is -wf, so it searchs -wf and returns the file name.
Returns:
The weights configuration file name. NULL if weights file isn't introduced.
Definition at line 264 of file ParamReader.cpp.
References WeightsFile.
Referenced by main().
bool ParamReader::CheckInfo ()
It checks if the -info option is enabled.
It checks if the -info option is enabled. The argument indicator for network information is -info, so it searchs -info.
Returns:
True if the -info option is enabled. False in other case.
Definition at line 268 of file ParamReader.cpp.
References NetworkInfo.
Referenced by main().
double ParamReader::GetSimulationStepTime ()
It gets the simulation step time.
It gets the simulation step time. The argument indicator for simulation step time is -st, so it searchs -st and returns the value as a float.
Returns:
The simulation step time. -1 if this option isn't enabled.
Definition at line 272 of file ParamReader.cpp.
References SimulationStepTime.
Referenced by main().
vector< InputSpikeDriver * > ParamReader::GetInputSpikeDrivers ()
It gets the input drivers.
It gets the input drivers of the simulation. The argument indicator for weights configuration file is -sf, so it searchs -sf and returns the file name.
Returns:
A vector of the simulation input drivers.
Definition at line 276 of file ParamReader.cpp.
References InputDrivers.
Referenced by main().
vector< OutputSpikeDriver * > ParamReader::GetOutputSpikeDrivers ()
It gets the output drivers.
It gets the output drivers of the simulation. It has two kinds of output drivers: -of Output_File, -oc IPAddress:Port Server|Client and -ioc IPAddress:Port Server|Client. It adds all the output drivers.
Returns:
A vector of the simulation output drivers.
Definition at line 280 of file ParamReader.cpp.
References OutputDrivers.
Referenced by main().
vector< OutputSpikeDriver * > ParamReader::GetMonitorDrivers ()
It gets the monitoring drivers.
It gets the monitoring drivers of the simulation. -log Monitor_File. It adds all the monitoring drivers.
Returns:
A vector of the simulation monitor drivers.
Definition at line 284 of file ParamReader.cpp.
References MonitorDrivers.
Referenced by main().
vector< OutputWeightDriver * > ParamReader::GetOutputWeightDrivers ()
It gets the output weight drivers.
It gets the output weight drivers of the simulation. The argument indicator for final weights configuration file is -sf, so it searchs -sf and returns the file name.
Returns:
A vector of the simulation output drivers.
Definition at line 288 of file ParamReader.cpp.
References OutputWeightDrivers.
Referenced by main().
Member Data Documentation
double ParamReader::SimulationTime [private]
Total simulation time.
Definition at line 64 of file ParamReader.h.
Referenced by GetSimulationTime().
char* ParamReader::NetworkFile [private]
Network configuration file.
Definition at line 69 of file ParamReader.h.
Referenced by GetNetworkFile().
char* ParamReader::WeightsFile [private]
Weights configuration file.
Definition at line 74 of file ParamReader.h.
Referenced by GetWeightsFile().
double ParamReader::WeightTime [private]
Save weights step time
Definition at line 79 of file ParamReader.h.
Referenced by GetSaveWeightStepTime().
bool ParamReader::NetworkInfo [private]
Network info?
Definition at line 84 of file ParamReader.h.
Referenced by CheckInfo().
double ParamReader::SimulationStepTime [private]
Simulation step time.
Definition at line 89 of file ParamReader.h.
Referenced by GetSimulationStepTime().
vector<InputSpikeDriver *> ParamReader::InputDrivers [private]
Input drivers.
Definition at line 95 of file ParamReader.h.
Referenced by GetInputSpikeDrivers().
vector<OutputSpikeDriver *> ParamReader::OutputDrivers [private]
Output drivers.
Definition at line 100 of file ParamReader.h.
Referenced by GetOutputSpikeDrivers().
vector<OutputSpikeDriver *> ParamReader::MonitorDrivers [private]
Output monitor.
Definition at line 105 of file ParamReader.h.
Referenced by GetMonitorDrivers().
vector<OutputWeightDriver *> ParamReader::OutputWeightDrivers [private]
Output drivers.
Definition at line 110 of file ParamReader.h.
Referenced by GetOutputWeightDrivers().
The documentation for this class was generated from the following files:
src/simulation/include/ParamReader.h
src/simulation/ParamReader.cpp