EDLUTKernel: WeightChange Class Reference
WeightChange Class Reference
Learning rule.
#include <WeightChange.h>
Public Member Functions
float GetMaxPos () const
It gets the maximum time of the learning rule.
void SetMaxPos (float NewMaxPos)
It sets the maximum time of the learning rule.
int GetNumExps () const
It gets the number of activity registers.
void SetNumExps (int NewNumExps)
It sets the number of activity registers.
float GetLparAt (int index) const
It gets the Lpar parameter of the learning rule.
void SetLparAt (int index, float NewLpar)
It sets the Lpar parameter of the learning rule.
float GetCparAt (int index) const
It gets the Cpar parameter of the learning rule.
void SetCparAt (int index, float NewCpar)
It sets the Cpar parameter of the learning rule.
int GetTrigger () const
It gets a trigger indicator.
void SetTrigger (int NewTrigger)
It sets a trigger indicator.
float GetA1Pre () const
It gets the A1 parameter.
void SetA1Pre (float NewA1Pre)
It sets the A1 parameter.
float GetA2PrePre () const
It gets the A2 parameter.
void SetA2PrePre (float NewA2PrePre)
It sets the A2 parameter.
virtual void ApplyWeightChange (Interconnection *Connection, double SpikeTime)=0
It applys the weight change function.
Private Attributes
float maxpos
int numexps
float lpar [3]
float cpar [3]
int trigger
float a1pre
float a2prepre
Detailed Description
Learning rule.
This class abstract the behaviour of a learning rule.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 27 of file WeightChange.h.
Member Function Documentation
float WeightChange::GetMaxPos () const
It gets the maximum time of the learning rule.
It gets the maximum time of the learning rule.
Returns:
The maximum time of the learning rule.
Definition at line 8 of file WeightChange.cpp.
References maxpos.
Referenced by Network::GetNetInfo().
void WeightChange::SetMaxPos (float NewMaxPos)
It sets the maximum time of the learning rule.
It sets the maximum time of the learning rule.
Parameters:
NewMaxPos The maximum time of the learning rule.
Definition at line 12 of file WeightChange.cpp.
References maxpos.
Referenced by Network::LoadNet().
int WeightChange::GetNumExps () const
It gets the number of activity registers.
It gets the number of activity registers.
Returns:
The number of activity registers.
Definition at line 16 of file WeightChange.cpp.
References numexps.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), and Network::LoadNet().
void WeightChange::SetNumExps (int NewNumExps)
It sets the number of activity registers.
It sets the number of activity registers.
Parameters:
NewNumExps The number of activity registers.
Definition at line 20 of file WeightChange.cpp.
References numexps.
Referenced by Network::LoadNet().
float WeightChange::GetLparAt (int index) const
It gets the Lpar parameter of the learning rule.
It gets the Lpar parameter of the learning rule.
Parameters:
index Parameter index.
Returns:
Lpar parameter at indexth position.
Definition at line 24 of file WeightChange.cpp.
References lpar.
Referenced by MultiplicativeWeightChange::ApplyWeightChange().
void WeightChange::SetLparAt (int index, float NewLpar)
It sets the Lpar parameter of the learning rule.
It sets the Lpar parameter of the learning rule.
Parameters:
index Parameter index.
NewLpar parameter at indexth position.
Definition at line 28 of file WeightChange.cpp.
References lpar.
Referenced by Network::LoadNet().
float WeightChange::GetCparAt (int index) const
It gets the Cpar parameter of the learning rule.
It gets the Cpar parameter of the learning rule.
Parameters:
index Parameter index.
Returns:
Cpar parameter at indexth position.
Definition at line 32 of file WeightChange.cpp.
References cpar.
Referenced by MultiplicativeWeightChange::ApplyWeightChange().
void WeightChange::SetCparAt (int index, float NewCpar)
It sets the Cpar parameter of the learning rule.
It sets the Cpar parameter of the learning rule.
Parameters:
index Parameter index.
NewCpar parameter at indexth position.
Definition at line 36 of file WeightChange.cpp.
References cpar.
Referenced by Network::LoadNet().
int WeightChange::GetTrigger () const
It gets a trigger indicator.
It gets a trigger indicator.
Returns:
The trigger indicator of the learning rule.
Definition at line 40 of file WeightChange.cpp.
References trigger.
Referenced by Network::GetNetInfo().
void WeightChange::SetTrigger (int NewTrigger)
It sets a trigger indicator.
It sets a trigger indicator.
Parameters:
NewTrigger The trigger indicator of the learning rule.
Definition at line 44 of file WeightChange.cpp.
References trigger.
Referenced by Network::LoadNet().
float WeightChange::GetA1Pre () const
It gets the A1 parameter.
It gets the A1 parameter.
Returns:
The A1 parameter.
Definition at line 48 of file WeightChange.cpp.
References a1pre.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), and Network::GetNetInfo().
void WeightChange::SetA1Pre (float NewA1Pre)
It sets the A1 parameter.
It sets the A1 parameter.
Parameters:
NewA1Pre The A1 parameter.
Definition at line 52 of file WeightChange.cpp.
References a1pre.
Referenced by Network::LoadNet().
float WeightChange::GetA2PrePre () const
It gets the A2 parameter.
It gets the A2 parameter.
Returns:
The A2 parameter.
Definition at line 56 of file WeightChange.cpp.
References a2prepre.
Referenced by MultiplicativeWeightChange::ApplyWeightChange(), AdditiveWeightChange::ApplyWeightChange(), and Network::GetNetInfo().
void WeightChange::SetA2PrePre (float NewA2PrePre)
It sets the A2 parameter.
It sets the A2 parameter.
Parameters:
NewA2PrePre The A2 parameter.
Definition at line 60 of file WeightChange.cpp.
References a2prepre.
Referenced by Network::LoadNet().
virtual void WeightChange::ApplyWeightChange (Interconnection * Connection, double SpikeTime) [pure virtual]
It applys the weight change function.
It applys the weight change function.
Parameters:
Connection The connection where the spike happened.
SpikeTime The spike time.
Implemented in AdditiveWeightChange, and MultiplicativeWeightChange.
Referenced by Interconnection::ChangeWeights().
Member Data Documentation
float WeightChange::maxpos [private]
Maximum time of the learning rule.
Definition at line 33 of file WeightChange.h.
Referenced by GetMaxPos(), and SetMaxPos().
int WeightChange::numexps [private]
Number of activity registers.
Definition at line 38 of file WeightChange.h.
Referenced by GetNumExps(), and SetNumExps().
float WeightChange::lpar[3] [private]
Activity register.
Definition at line 43 of file WeightChange.h.
Referenced by GetLparAt(), and SetLparAt().
float WeightChange::cpar[3] [private]
Activity register.
Definition at line 48 of file WeightChange.h.
Referenced by GetCparAt(), and SetCparAt().
int WeightChange::trigger [private]
This weight change is a trigger.
Definition at line 53 of file WeightChange.h.
Referenced by GetTrigger(), and SetTrigger().
float WeightChange::a1pre [private]
Learning rule parameter 1.
Definition at line 58 of file WeightChange.h.
Referenced by GetA1Pre(), and SetA1Pre().
float WeightChange::a2prepre [private]
Learning rule parameter 2.
Definition at line 63 of file WeightChange.h.
Referenced by GetA2PrePre(), and SetA2PrePre().
The documentation for this class was generated from the following files:
src/spike/include/WeightChange.h
src/spike/WeightChange.cpp