EDLUTKernel: ConnectionException Class Reference
ConnectionException Class Reference
Exception in the connection process.
#include <ConnectionException.h>
Public Member Functions
ConnectionException (string TargetAddress, unsigned short TargetPort, string ErrorMessage)
Class constructor.
string GetAddress () const
It gets the connection target address.
unsigned short GetPort () const
It gets the connection target port.
string GetErrorMsg () const
It gets the error message.
void display_error () const
It prints in the standard error the error message of this exception.
Private Attributes
string Address
unsigned short Port
string Message
Detailed Description
Exception in the connection process.
This class abstract the behaviour of an exception in the connection process. This exception could happen by different reasons...).
Author:
Jesus Garrido
Date:
September 2008
Definition at line 29 of file ConnectionException.h.
Constructor & Destructor Documentation
ConnectionException::ConnectionException (string TargetAddress, unsigned short TargetPort, string ErrorMessage)
Class constructor.
Class constructor with parameters.
Parameters:
TargetAddress Target address of the connection.
TargetPort Target port of the connection.
ErrorMessage Message describing the error.
Definition at line 3 of file ConnectionException.cpp.
Member Function Documentation
string ConnectionException::GetAddress () const
It gets the connection target address.
It gets the connection target address.
Returns:
The connection target address.
Definition at line 6 of file ConnectionException.cpp.
References Address.
Referenced by operator<<().
unsigned short ConnectionException::GetPort () const
It gets the connection target port.
It gets the connection target port.
Returns:
The connection target port.
Definition at line 10 of file ConnectionException.cpp.
References Port.
Referenced by operator<<().
string ConnectionException::GetErrorMsg () const
It gets the error message.
It gets the error that threw the error.
Returns:
The error message.
Definition at line 14 of file ConnectionException.cpp.
References Message.
Referenced by operator<<().
void ConnectionException::display_error () const
It prints in the standard error the error message of this exception.
It prints in the standard error the error message of this exception.
Definition at line 18 of file ConnectionException.cpp.
References Address, Message, and Port.
Member Data Documentation
string ConnectionException::Address [private]
Target Address.
Definition at line 35 of file ConnectionException.h.
Referenced by display_error(), and GetAddress().
unsigned short ConnectionException::Port [private]
Target Port.
Definition at line 40 of file ConnectionException.h.
Referenced by display_error(), and GetPort().
string ConnectionException::Message [private]
Error message.
Definition at line 45 of file ConnectionException.h.
Referenced by display_error(), and GetErrorMsg().
The documentation for this class was generated from the following files:
src/communication/include/ConnectionException.h
src/communication/ConnectionException.cpp