EDLUTKernel: InputSpike Class Reference
InputSpike Class Reference
Neural network spike. Input external spike.
#include <InputSpike.h>
Public Member Functions
InputSpike ()
Default constructor.
InputSpike (double NewTime, Neuron *NewSource)
Constructor with parameters.
~InputSpike ()
Class destructor.
void ProcessEvent (Simulation *CurrentSimulation)
It process an event in the simulation.
Detailed Description
Neural network spike. Input external spike.
This class abstract the concept of input spike.
Author:
Jesus Garrido
Richard Carrillo
Date:
November 2008
Definition at line 35 of file InputSpike.h.
Constructor & Destructor Documentation
InputSpike::InputSpike ()
Default constructor.
It creates and initializes a new spike object.
Definition at line 8 of file InputSpike.cpp.
InputSpike::InputSpike (double NewTime, Neuron * NewSource)
Constructor with parameters.
It creates and initializes a new spike with the parameters.
Parameters:
NewTime Time of the new spike.
NewSource Source neuron of the spike.
Definition at line 11 of file InputSpike.cpp.
InputSpike::~InputSpike ()
Class destructor.
It destroies an object of this class.
Definition at line 14 of file InputSpike.cpp.
Member Function Documentation
void InputSpike::ProcessEvent (Simulation * CurrentSimulation) [virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implements Spike.
Definition at line 17 of file InputSpike.cpp.
References Neuron::GenerateOutputActivity(), Neuron::GetLastUpdate(), Simulation::GetQueue(), Spike::GetSource(), Neuron::GetStateVarAt(), Spike::source, Simulation::WritePotential(), and Simulation::WriteSpike().
The documentation for this class was generated from the following files:
src/spike/include/InputSpike.h
src/spike/InputSpike.cpp