EDLUTKernel: AdditiveWeightChange Class Reference
AdditiveWeightChange Class Reference
Additive learning rule.
#include <AdditiveWeightChange.h>
Public Member Functions
virtual void ApplyWeightChange (Interconnection *Connection, double SpikeTime)
It applys the weight change function.
Private Member Functions
void update_activity (double time, Interconnection *Connection, bool spike)
It updates the previous activity in the connection.
Detailed Description
Additive learning rule.
This class abstract the behaviour of a additive learning rule.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 27 of file AdditiveWeightChange.h.
Member Function Documentation
void AdditiveWeightChange::update_activity (double time, Interconnection * Connection, bool spike) [private]
It updates the previous activity in the connection.
It updates the previous activity in the connection.
Parameters:
time The spike time.
Connection The connection to be modified.
spike True if an spike is produced.
Definition at line 8 of file AdditiveWeightChange.cpp.
References Interconnection::GetActivityAt(), Interconnection::GetLastSpikeTime(), and Interconnection::SetActivityAt().
Referenced by ApplyWeightChange().
void AdditiveWeightChange::ApplyWeightChange (Interconnection * Connection, double SpikeTime) [virtual]
It applys the weight change function.
It applys the weight change function.
Parameters:
Connection The connection where the spike happened.
SpikeTime The spike time.
Implements WeightChange.
Definition at line 29 of file AdditiveWeightChange.cpp.
References WeightChange::GetA1Pre(), WeightChange::GetA2PrePre(), Interconnection::GetActivityAt(), Neuron::GetInputConnectionAt(), Neuron::GetInputNumber(), Interconnection::GetMaxWeight(), Interconnection::GetTarget(), Interconnection::GetWeight(), Interconnection::GetWeightChange(), Interconnection::SetLastSpikeTime(), Interconnection::SetWeight(), and update_activity().
The documentation for this class was generated from the following files:
src/spike/include/AdditiveWeightChange.h
src/spike/AdditiveWeightChange.cpp