EDLUTKernel: InternalSpike Class Reference
InternalSpike Class Reference
Neural network internal spike.
#include <InternalSpike.h>
Public Member Functions
InternalSpike ()
Default constructor.
InternalSpike (double NewTime, Neuron *NewSource)
Constructor with parameters.
~InternalSpike ()
Class destructor.
void ProcessEvent (Simulation *CurrentSimulation)
It process an event in the simulation.
Detailed Description
Neural network internal spike.
This class abstract the concept of spike. An internal spike is an event generated by the own cell without external excitation.
Author:
Jesus Garrido
Richard Carrillo
Date:
November 2008
Definition at line 35 of file InternalSpike.h.
Constructor & Destructor Documentation
InternalSpike::InternalSpike ()
Default constructor.
It creates and initializes a new spike object.
Definition at line 10 of file InternalSpike.cpp.
InternalSpike::InternalSpike (double NewTime, Neuron * NewSource)
Constructor with parameters.
It creates and initializes a new spike with the parameters.
Parameters:
NewTime Time of the new spike.
NewSource Source neuron of the spike.
Definition at line 13 of file InternalSpike.cpp.
InternalSpike::~InternalSpike ()
Class destructor.
It destroies an object of this class.
Definition at line 16 of file InternalSpike.cpp.
Member Function Documentation
void InternalSpike::ProcessEvent (Simulation * CurrentSimulation) [virtual]
It process an event in the simulation.
It process the event in the simulation.
Parameters:
CurrentSimulation The simulation object where the event is working.
Implements Spike.
Definition at line 19 of file InternalSpike.cpp.
References Neuron::GenerateAutoActivity(), Neuron::GenerateOutputActivity(), Neuron::GetLastUpdate(), Neuron::GetPredictedSpike(), Simulation::GetQueue(), Spike::GetSource(), Neuron::GetStateVarAt(), Neuron::ProcessInputActivity(), Spike::source, Event::time, Simulation::WritePotential(), and Simulation::WriteSpike().
The documentation for this class was generated from the following files:
src/spike/include/InternalSpike.h
src/spike/InternalSpike.cpp