EDLUTKernel: Network Class Reference
Network Class Reference
Spiking neural network.
#include <Network.h>
Public Member Functions
Network (const char *netfile, const char *wfile, EventQueue *Queue) throw (EDLUTException)
It creates a new network object by loading the configuration and the weights from files.
~Network ()
Default destructor.
Neuron * GetNeuronAt (int index) const
It gets a neuron by the index.
int GetNeuronNumber () const
It gets the number of neurons in the network.
void SaveWeights (const char *wfile) throw (EDLUTException)
It saves the weights in a file.
ostream & GetNetInfo (ostream &out) const
It prints the network info.
Private Member Functions
void FindOutConnections ()
It sorts the connections by the source neuron and the delay and add the output connections.
void FindInConnections ()
It adds the input connection to the target neuron.
void SetWeightOrdination ()
It sorts the connections by the connection index.
NeuronType * LoadNetTypes (char *neutype) throw (EDLUTException)
It loads the neuron type characteristics.
void InitNetPredictions (EventQueue *Queue)
It inits the spikes predictions of every neuron in the network.
void LoadNet (const char *netfile) throw (EDLUTException)
It loads the network configuration from a file.
void LoadWeights (const char *wfile) throw (EDLUTFileException)
It loads the connection synaptic weights from a file.
void LoadNeuronTypeTables () throw (EDLUTException)
It loads the neuron model tables of this network.
Private Attributes
Interconnection * inters
Network interconnections.
int ninters
Number of interconnections.
NeuronType * neutypes
Neuron types.
int nneutypes
Neuron types number.
Neuron * neurons
Neuron array.
int nneurons
Number of neurons.
WeightChange ** wchanges
Learning rules.
int nwchanges
Number of learning rules.
Interconnection ** wordination
Initial connection ordenation.
Detailed Description
Spiking neural network.
This class abstract the behaviour of a spiking neural network. It is composed by interconnections, neurons, neuron types and weight changes.
Author:
Jesus Garrido
Richard Carrillo
Date:
August 2008
Definition at line 38 of file Network.h.
Constructor & Destructor Documentation
Network::Network (const char * netfile, const char * wfile, EventQueue * Queue) throw (EDLUTException)
It creates a new network object by loading the configuration and the weights from files.
It creates a new network object. The network is loaded from the configuration file, and the weights are loaded from his file. Finally, it initializes the event queue with the initial spikes.
Parameters:
netfile The network configuration file name.
wfile The weight file name.
Queue The event queue where the events will be inserted.
Exceptions:
EDLUTException If some error has happened.
Definition at line 83 of file Network.cpp.
References InitNetPredictions(), LoadNet(), LoadNeuronTypeTables(), and LoadWeights().
Network::~Network ()
Default destructor.
It destroies a network object and frees the memory.
Definition at line 90 of file Network.cpp.
References inters, neurons, neutypes, wchanges, and wordination.
Member Function Documentation
void Network::FindOutConnections () [private]
It sorts the connections by the source neuron and the delay and add the output connections.
It sorts the connections by the source neuron (from the lowest to the highest index) and by the connection delay. It adds the connections to the output connections of the source neuron.
Postcondition:
The connections will be sorted by source neuron and delay.
Definition at line 29 of file Network.cpp.
References Neuron::AddOutputConnection(), Interconnection::GetSource(), inters, ninters, and qsort_inters().
Referenced by LoadNet().
void Network::FindInConnections () [private]
It adds the input connection to the target neuron.
It adds the connections to the input connections of the target neuron.
Definition at line 48 of file Network.cpp.
References Neuron::AddInputConnection(), Interconnection::GetTarget(), inters, and ninters.
Referenced by LoadNet().
void Network::SetWeightOrdination () [private]
It sorts the connections by the connection index.
It sorts the connections by the connection index. This ordination is the ordenation needed for the weight load. The ordination will be in wordination field.
Definition at line 39 of file Network.cpp.
References Interconnection::GetIndex(), inters, ninters, and wordination.
Referenced by LoadNet().
NeuronType * Network::LoadNetTypes (char * neutype) throw (EDLUTException) [private]
It loads the neuron type characteristics.
It checks if the neuron type has been loaded, and in other case, it loads the characteristics from the neuron type files.
Parameters:
neutype The name of the neuron type to load.
Returns:
The loaded (or existing) neuron type.
Exceptions:
EDLUTException If the neuron model file hasn't been able to be correctly readed.
Definition at line 56 of file Network.cpp.
References NeuronType::GetId(), NeuronType::LoadNeuronType(), neutypes, and nneutypes.
Referenced by LoadNet().
void Network::InitNetPredictions (EventQueue * Queue) [private]
It inits the spikes predictions of every neuron in the network.
It adds all the spike predictions in the network in the initial conditions.
Parameters:
Queue The event queue where the spikes will be added.
Definition at line 77 of file Network.cpp.
References neurons, and nneurons.
Referenced by Network().
void Network::LoadNet (const char * netfile) throw (EDLUTException) [private]
It loads the network configuration from a file.
It loads a new network from a file.
Parameters:
netfile The file name of the network configuration file.
Exceptions:
EDLUTFileException If the network configuration file hasn't been able to be correctly readed.
Definition at line 106 of file Network.cpp.
References Interconnection::ClearActivity(), NeuronType::ClearNeuronType(), FindInConnections(), FindOutConnections(), WeightChange::GetNumExps(), Neuron::InitNeuron(), inters, LoadNetTypes(), MAXIDSIZE, MAXIDSIZEC, neurons, neutypes, ninters, nneurons, nneutypes, nwchanges, WeightChange::SetA1Pre(), WeightChange::SetA2PrePre(), WeightChange::SetCparAt(), Interconnection::SetDelay(), Interconnection::SetIndex(), Interconnection::SetLastSpikeTime(), WeightChange::SetLparAt(), WeightChange::SetMaxPos(), Interconnection::SetMaxWeight(), WeightChange::SetNumExps(), Interconnection::SetSource(), Interconnection::SetTarget(), WeightChange::SetTrigger(), Interconnection::SetType(), Interconnection::SetWeight(), Interconnection::SetWeightChange(), SetWeightOrdination(), skip_comments(), and wchanges.
Referenced by Network().
void Network::LoadWeights (const char * wfile) throw (EDLUTFileException) [private]
It loads the connection synaptic weights from a file.
It loads the connection synaptic weights from a file.
Parameters:
wfile The file name of the weights file.
Precondition:
The network connections are sorted by the index in the field wordenation.
See also:
SetWeightOrdenation()
Exceptions:
EDLUTFileException If the weights file hasn't been able to be correctly readed.
Definition at line 280 of file Network.cpp.
References Interconnection::GetMaxWeight(), ninters, Interconnection::SetWeight(), skip_comments(), and wordination.
Referenced by Network().
void Network::LoadNeuronTypeTables () throw (EDLUTException) [private]
It loads the neuron model tables of this network.
It loads all the neuron model tables of this network.
Precondition:
The neuron types have been loaded before.
Exceptions:
EDLUTException If the neuron model table file hasn't been able to be correctly readed.
Definition at line 366 of file Network.cpp.
References NeuronType::LoadTables(), neutypes, and nneutypes.
Referenced by Network().
Neuron * Network::GetNeuronAt (int index) const
It gets a neuron by the index.
It returns a neuron from the index.
Parameters:
index The index of the neuron to get.
Returns:
The neuron whose index is the parameter.
Definition at line 98 of file Network.cpp.
References neurons.
int Network::GetNeuronNumber () const
It gets the number of neurons in the network.
It gets the number of neurons in the network.
Returns:
The number of neurons.
Definition at line 102 of file Network.cpp.
References nneurons.
void Network::SaveWeights (const char * wfile) throw (EDLUTException)
It saves the weights in a file.
It saves the network weights in a file.
Parameters:
wfile The file name where we save the weights.
Exceptions:
EDLUTException If some error happends.
Definition at line 318 of file Network.cpp.
References Interconnection::GetWeight(), ninters, and wordination.
ostream & Network::GetNetInfo (ostream & out) const
It prints the network info.
It prints the current network characteristics (number of neurons, types, connections...).
Parameters:
out The stream where it prints the information.
Returns:
The stream after the printer.
Definition at line 373 of file Network.cpp.
References WeightChange::GetA1Pre(), WeightChange::GetA2PrePre(), Interconnection::GetDelay(), NeuronType::GetId(), Neuron::GetIndex(), Neuron::GetLastUpdate(), WeightChange::GetMaxPos(), Neuron::GetNeuronType(), Neuron::GetOutputNumber(), Neuron::GetPredictedSpike(), Interconnection::GetSource(), Neuron::GetStateVarAt(), NeuronType::GetStateVarsNumber(), NeuronType::GetTableNumber(), Interconnection::GetTarget(), WeightChange::GetTrigger(), Interconnection::GetType(), inters, Neuron::IsMonitored(), neurons, neutypes, ninters, nneurons, nneutypes, nwchanges, and wchanges.
Member Data Documentation
Interconnection* Network::inters [private]
Network interconnections.
Definition at line 44 of file Network.h.
Referenced by FindInConnections(), FindOutConnections(), GetNetInfo(), LoadNet(), SetWeightOrdination(), and ~Network().
int Network::ninters [private]
Number of interconnections.
Definition at line 49 of file Network.h.
Referenced by FindInConnections(), FindOutConnections(), GetNetInfo(), LoadNet(), LoadWeights(), SaveWeights(), and SetWeightOrdination().
NeuronType* Network::neutypes [private]
Neuron types.
Definition at line 54 of file Network.h.
Referenced by GetNetInfo(), LoadNet(), LoadNetTypes(), LoadNeuronTypeTables(), and ~Network().
int Network::nneutypes [private]
Neuron types number.
Definition at line 59 of file Network.h.
Referenced by GetNetInfo(), LoadNet(), LoadNetTypes(), and LoadNeuronTypeTables().
Neuron* Network::neurons [private]
Neuron array.
Definition at line 64 of file Network.h.
Referenced by GetNetInfo(), GetNeuronAt(), InitNetPredictions(), LoadNet(), and ~Network().
int Network::nneurons [private]
Number of neurons.
Definition at line 69 of file Network.h.
Referenced by GetNetInfo(), GetNeuronNumber(), InitNetPredictions(), and LoadNet().
WeightChange** Network::wchanges [private]
Learning rules.
Definition at line 74 of file Network.h.
Referenced by GetNetInfo(), LoadNet(), and ~Network().
int Network::nwchanges [private]
Number of learning rules.
Definition at line 79 of file Network.h.
Referenced by GetNetInfo(), and LoadNet().
Interconnection** Network::wordination [private]
Initial connection ordenation.
Definition at line 84 of file Network.h.
Referenced by LoadWeights(), SaveWeights(), SetWeightOrdination(), and ~Network().
The documentation for this class was generated from the following files:
src/spike/include/Network.h
src/spike/Network.cpp